### ISSUE TITLE
Error : Cannot import name 'multiarray' 

### ISSUE THREAD

**Issue by lrmodesgh** [domlysz/BlenderGIS#103]
i have installed numpy.
but i do not know why i get this error when i try to install blender gis plugin.

**Comment by manirajarvind** [comment]
I'm too getting the same ERROR!
Blender console reported the following traceback.

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/home/kat/.config/blender/2.78/scripts/addons/BlenderGIS-master/__init__.py", line 39, in <module>
    from .core.checkdeps import HAS_GDAL, HAS_PYPROJ, HAS_PIL, HAS_IMGIO
  File "/home/kat/.config/blender/2.78/scripts/addons/BlenderGIS-master/core/__init__.py", line 6, in <module>
    from .utils import XY, BBOX
  File "/home/kat/.config/blender/2.78/scripts/addons/BlenderGIS-master/core/utils/__init__.py", line 3, in <module>
    from .gradient import Color, Stop, Gradient
  File "/home/kat/.config/blender/2.78/scripts/addons/BlenderGIS-master/core/utils/gradient.py", line 8, in <module>
    from ..maths import akima
  File "/home/kat/.config/blender/2.78/scripts/addons/BlenderGIS-master/core/maths/akima.py", line 81, in <module>
    import numpy
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
Original error was: cannot import name 'multiarray'

**Comment by lrmodesgh** [comment]
yay !... issue was resolved.

one has to install python 3.6 and also need to install numpy using pip after that.
since, blendergis plugin is written with python3.6 and uses numpy module multiarray - which was not available in python 3.5, the plugin was not working. 

so, prerequesite is to have python 3.6 and corresponding numpy.
