### ISSUE TITLE
Georaster DEM import fail when 'mesh' subdivision

### ISSUE THREAD

**Issue by thmxv** [domlysz/BlenderGIS#105]
When import a georaster DEM and trying to use mesh subdivision, the script crahes.:

Traceback (most recent call last):
  File "/home/xavier/.config/blender/2.79/scripts/addons/BlenderGIS-master/operators/io_import_georaster.py", line 363, in execute
    bpy.ops.mesh.loopcut(number_cuts = grid.size.x - 1, edge_index = 1)
  File "/usr/share/blender/2.79/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.mesh.loopcut.poll() expected a view3d region & editmesh

**Comment by PayamT** [comment]
Use subsurf. 


Sent from Yahoo Mail for iPhone


On Thursday, March 22, 2018, 11:57 AM, Xavier Thomas <notifications@github.com> wrote:


When import a georaster DEM and trying to use mesh subdivision, the script crahes.:

Traceback (most recent call last):
File "/home/xavier/.config/blender/2.79/scripts/addons/BlenderGIS-master/operators/io_import_georaster.py", line 363, in execute
bpy.ops.mesh.loopcut(number_cuts = grid.size.x - 1, edge_index = 1)
File "/usr/share/blender/2.79/scripts/modules/bpy/ops.py", line 189, in call
ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.mesh.loopcut.poll() expected a view3d region & editmesh

**Comment by thmxv** [comment]
Surbsurf does not crash but is not what I need. But I can use subsurf or continue from where the addon crash and than remove/add the modifiers and do the correct amount of loop cut manually.

**Comment by domlysz** [comment]
Fixed. Loopcut operator is no longer used.
