### ISSUE TITLE
RuntimeError: Error: Non overlap data

### ISSUE THREAD

**Issue by jaythub** [domlysz/BlenderGIS#124]
After following your https://github.com/domlysz/BlenderGIS/wiki/Quick-start, when i "Get SRTM"

Traceback (most recent call last):
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/operators/io_get_srtm.py", line 40, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/operators/io_get_srtm.py", line 128, in execute
    fillNodata = False)
  File "/usr/share/blender/scripts/modules/bpy/ops.py", line 187, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Non overlap data

location: <unknown location>:-1

**Comment by domlysz** [comment]
Thank you for reporting this issue, it's now fixed 89f1e7a
