### ISSUE TITLE
KeyError: 277

### ISSUE THREAD

**Issue by jaythub** [domlysz/BlenderGIS#125]
After following your https://github.com/domlysz/BlenderGIS/wiki/Quick-start, when i "Get SRTM"

Traceback (most recent call last):
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/operators/io_get_srtm.py", line 40, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/operators/io_get_srtm.py", line 130, in execute
    fillNodata = False)
  File "/usr/share/blender/scripts/modules/bpy/ops.py", line 187, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/operators/io_import_georaster.py", line 360, in execute
    grid = bpyGeoRaster(filePath, subBoxGeo=subBox, clip=self.clip, fillNodata=self.fillNodata, useGDAL=HAS_GDAL)
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/operators/utils/georaster_utils.py", line 256, in __init__
    GeoRaster.__init__(self, filepath, useGDAL=useGDAL)
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/core/georaster/georaster.py", line 66, in __init__
    self._fromTIFF()
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/core/georaster/georaster.py", line 125, in _fromTIFF
    self.nbBands = tif['SamplesPerPixel']
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/core/lib/Tyf/ifd.py", line 111, in __getitem__
    return dict.__getitem__(self, tags._2tag(tag))._decode()
KeyError: 277

**Comment by domlysz** [comment]
Please, can you provide me a .blend file to test ? I have no problem for my side, maybe it's related to the location of the srtm request which return another kind of tiff file.

**Comment by jaythub** [comment]
I noticed the line "no raster reprojection support" in the basemap dialog. 

Anyway below is a zip containing the .blend, .tifs and .wld
[GisTest.zip](https://github.com/domlysz/BlenderGIS/files/2295298/GisTest.zip)

**Comment by domlysz** [comment]
I don't know what happen here, it works correctly for me. Can you import the file srtm_bgis.tif (menu file > import > georeferenced raster) with the following setup ?

![selection_041](https://user-images.githubusercontent.com/5639024/44269565-328f0400-a235-11e8-8097-5667e4f0b2ca.jpg)

**Comment by jaythub** [comment]
I got this using the settings you asked.

Traceback (most recent call last):
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/operators/io_import_georaster.py", line 360, in execute
    grid = bpyGeoRaster(filePath, subBoxGeo=subBox, clip=self.clip, fillNodata=self.fillNodata, useGDAL=HAS_GDAL)
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/operators/utils/georaster_utils.py", line 225, in __init__
    GeoRaster.__init__(self, path, subBoxGeo=subBoxGeo, useGDAL=useGDAL)
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/core/georaster/georaster.py", line 66, in __init__
    self._fromTIFF()
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/core/georaster/georaster.py", line 125, in _fromTIFF
    self.nbBands = tif['SamplesPerPixel']
  File "/home/jay/.config/blender/2.79/scripts/addons/BlenderGIS-master/core/lib/Tyf/ifd.py", line 111, in __getitem__
    return dict.__getitem__(self, tags._2tag(tag))._decode()
KeyError: 277

location: <unknown location>:-1

**Comment by berenm** [comment]
This also happened to me when downloading SRTM data, but I fixed it by installing the python-gdal package for python3. I believe the issue happens when GDAL is not available.

**Comment by domlysz** [comment]
Right, installing gdal will solve the issue, but it must also works without. What are yours operating systems?

**Comment by jaythub** [comment]
I just tested on windows 10 blender 2.79. No GDAL. I

**Comment by jaythub** [comment]
So i don't know why my linux mint PC does not work. I'll try installing gdal and see what happens

**Comment by domlysz** [comment]
I'm also on linux mint and it works. Are you in 32 or 64bits. What mint version

**Comment by jaythub** [comment]
linux mint 19 64bit. Numpy and python 3.6 installed. No GDAL

**Comment by jaythub** [comment]
The working windows 10 blender 2.79 has python 3.5. It's possible that may be the cause.

**Comment by domlysz** [comment]
Finally found how to reproduce and fix it. This issue had the same origin as #127, related to the usage of PIL library when available on the system. Short story : srtm files must be cast to float 32 before the import and PIL can potentially be used to save this new file on disc, but when it does, the resulting file does not contains the required tag named SamplesPerPixel, that's why the raise an error when searching for this tag.

Last commit b0ccd6d fix the issue avoiding to use PIL if there are better alternatives.

And so Python 3.6 is not to blame here!
