### ISSUE TITLE
SRTM import raise unsupported format

### ISSUE THREAD

**Issue by huiyao8761380** [domlysz/BlenderGIS#138]
![ov2okoyw1 o1b4gzpit2gnj](https://user-images.githubusercontent.com/22783500/49064259-565ede80-f255-11e8-93dd-5c17bbb7ff4a.png)

**Comment by huiyao8761380** [comment]
Unable to generate height map

**Comment by huiyao8761380** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 40, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 112, in execute
    subdivision = 'subsurf')
  File "D:\Blender\2.79\scripts\modules\bpy\ops.py", line 187, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: 错误: Unsupported format


location: <unknown location>:-1

**Comment by domlysz** [comment]
Please reopen with more information if you still encounter this issue
