### ISSUE TITLE
Get SRTM button returns error

### ISSUE THREAD

**Issue by Tilix4** [domlysz/BlenderGIS#142]
Blender 2.79b / BlenderGIS commit : *1eb3346*

For any tile, clicking **Get SRTM** returns :
````
Traceback (most recent call last):
  File "C:\Users\fdavid\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 40, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\fdavid\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 97, in execute
    with urlopen(rq) as response, open(filePath, 'wb') as outFile:
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\urllib\request.py", line 504, in error
    result = self._call_chain(*args)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\urllib\request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\urllib\request.py", line 1257, in do_open
    r = h.getresponse()
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\http\client.py", line 1198, in getresponse
    response.begin()
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Une connexion existante a dû être fermée par l’hôte distant

location: <unknown location>:-1


````

**Comment by domlysz** [comment]
Are you still encounter this issue?

**Comment by Tilix4** [comment]
Yes. On two different computers.

**Comment by rossoe** [comment]
I am getting the same issue running on 2.8 version trying to use the Get  SRTM feature -

![srtm](https://user-images.githubusercontent.com/28996048/56248144-031fe800-609f-11e9-8cd8-53a9c278db15.JPG)

Error in Blender debug console:
`ERROR:BlenderGIS-Blender28.operators.io_get_srtm:Http request fails url:http://opentopo.sdsc.edu/otr/getdem?demtypes=SRTMGL3&west=-1.4908599062984698&east=-1.48662786246088&south=-0.002050742663107441&north=0.002050742663107441&outputFormat=GTiff, code:500, error:Internal Server Error`

Stripping the URL out -
[http://opentopo.sdsc.edu/otr/getdem?demtypes=SRTMGL3&west=-1.4908599062984698&east=-1.48662786246088&south=-0.002050742663107441&north=0.002050742663107441&outputFormat=GTiff](http://opentopo.sdsc.edu/otr/getdem?demtypes=SRTMGL3&west=-1.4908599062984698&east=-1.48662786246088&south=-0.002050742663107441&north=0.002050742663107441&outputFormat=GTiff)
and placing in browser returns a bit more debug info from Apache

**Comment by domlysz** [comment]
@rossoe please update the addon there is a typo in the url it's not _demtypes_ but _demtype_ (without s). Bad luck you have downloaded the addon between 22 and 23 march, a wrong commit from my side.

**Comment by rossoe** [comment]
yep that solved it thanks. One thing i'm noticing is that you can't get a sat image to layer over the SRTM mesh in 2.8 as per you see happening in the vid on 2.7 ver - https://raw.githubusercontent.com/wiki/domlysz/blenderGIS/Blender27x/images/srtm_demo.gif

I can get around it by placing the sat image down, then 'Get SRTM' - delete the sat image - then add sat image back in again selecting 'on mesh' when importing.

**Comment by domlysz** [comment]
It's possible to apply directly STRM to a sat image, make sure to select the plane mesh before push get srtm button, if you use basemaps then you must firstly export the maps to a new plane mesh by pressing E key (as explained in the [quick start guide](https://github.com/domlysz/BlenderGIS/wiki/Quick-start))

**Comment by Rikssss** [comment]
i'm having the same problem (can't use srtm feature) at the moment and don't know how to solve it...

**Comment by domlysz** [comment]
See #305
