### ISSUE TITLE
Cannot import name 'multiarray' from 'numpy.core'

### ISSUE THREAD

**Issue by rinelb** [domlysz/BlenderGIS#225]
Im running Ubuntu 18.04.3 LTS

i installed blender 2.8 as follows 
from https://askubuntu.com/questions/1105556/how-to-completely-uninstall-blender
sudo add-apt-repository ppa:thomas-schiex/blender
sudo apt-get update
sudo apt-get install blender

installed python 3.7 

then installed
sudo apt install python3-pip

and installed numpy using: 
pip3 install numpy

**when i enable Blendergis i get this error**

Read prefs: /home/test/.config/blender/2.82/config/userpref.blend
ERROR:BlenderGIS-master.core.checkdeps:42:Cannot install ImageIO's Freeimage plugin
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/.config/blender/2.82/scripts/addons/BlenderGIS-master/core/checkdeps.py", line 39, in <module>
    from .lib import imageio
  File "/home/test/.config/blender/2.82/scripts/addons/BlenderGIS-master/core/lib/imageio/__init__.py", line 20, in <module>
    from .core import FormatManager, RETURN_BYTES  # noqa
  File "/home/test/.config/blender/2.82/scripts/addons/BlenderGIS-master/core/lib/imageio/core/__init__.py", line 9, in <module>
    from .util import Image, Dict, asarray, image_as_uint, urlopen  # noqa
  File "/home/test/.config/blender/2.82/scripts/addons/BlenderGIS-master/core/lib/imageio/core/util.py", line 18, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/__init__.py)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/test/.config/blender/2.82/scripts/addons/BlenderGIS-master/__init__.py", line 67, in <module>
    from .core.settings import getSettings, setSettings
  File "/home/test/.config/blender/2.82/scripts/addons/BlenderGIS-master/core/__init__.py", line 8, in <module>
    from .utils import XY, BBOX
  File "/home/test/.config/blender/2.82/scripts/addons/BlenderGIS-master/core/utils/__init__.py", line 3, in <module>
    from .gradient import Color, Stop, Gradient
  File "/home/test/.config/blender/2.82/scripts/addons/BlenderGIS-master/core/utils/gradient.py", line 9, in <module>
    from ..maths import akima
  File "/home/test/.config/blender/2.82/scripts/addons/BlenderGIS-master/core/maths/akima.py", line 81, in <module>
    import numpy
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/__init__.py)

**Comment by s-leger** [comment]
Take a look at issue #103

**Comment by eudoxos** [comment]
I am requesting addition to the page https://github.com/domlysz/BlenderGIS/wiki/Install-and-usage which has obsolete workaround to this issue.

Currently, under Ubuntu 18.04, blender 2.8 from the PPA links against python3.7 (whereas default python is 3.6, this running `pip3 install` will install for python3.6). Thus the command to install needed dependencies is:

```
python3.7 -m pip install numpy imageio
```

**Comment by domlysz** [comment]
Thanks, but as I can test the command fails because there is no Python3.7 binary (the PPA only install libpython3.7). Maybe I'm missing something.

**Comment by eudoxos** [comment]
Do `apt install python3.7`, it is available from standard 18.04 universe component. Of course, it is workaround for PPA packager's bug but should get you going.
