### ISSUE TITLE
Basemaps - NaN cast error

### ISSUE THREAD

**Issue by domlysz** [domlysz/BlenderGIS#228]
The error that goes with this 
![image](https://user-images.githubusercontent.com/17836911/70849811-c9002380-1e83-11ea-9da5-2eea3621f608.png)

_Originally posted by @MikeDabrowski in https://github.com/domlysz/BlenderGIS/issues/186#issuecomment-565720570_

**Comment by domlysz** [comment]
@MikeDabrowski please can you provide more detailed steps to reproduce this issue.

**Comment by pixeltumbler** [comment]
Hi @domlysz 
I seem to have a similar problem. 
All I do is clicking on GIS and choosing webgeodata > Basemap.
Source: Google
Layer: Satellite
Tile matrix: Web Mercator (source)

![blendergis](https://user-images.githubusercontent.com/59435159/71659515-36e39080-2d48-11ea-9104-a39c77121e8f.jpg)
![blendergis2](https://user-images.githubusercontent.com/59435159/71659588-6e523d00-2d48-11ea-8b4a-357dad0f82d4.jpg)

I have Windows 10 Home
Blender v.2.81a
I tried this with the latest BlenderGis downloaded today (2020-01-02)

```
Read prefs: C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.81\2.81\python
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 155, in run
    self.mosaic = self.request()
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 211, in request
    mosaic = self.srv.getImage(self.laykey, bbox, self.zoom, toDstGrid=toDstGrid, outCRS=self.crs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 821, in getImage
    rq = BBoxRequest(tm, bbox, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 298, in __init__
    self.firstCol, self.firstRow = tm.getTileNumber(xmin, ymax, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 232, in getTileNumber
    col = int(math.floor(col))
ValueError: cannot convert float NaN to integer

Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 155, in run
    self.mosaic = self.request()
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 211, in request
    mosaic = self.srv.getImage(self.laykey, bbox, self.zoom, toDstGrid=toDstGrid, outCRS=self.crs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 821, in getImage
    rq = BBoxRequest(tm, bbox, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 298, in __init__
    self.firstCol, self.firstRow = tm.getTileNumber(xmin, ymax, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 232, in getTileNumber
    col = int(math.floor(col))
ValueError: cannot convert float NaN to integer

```

**Comment by domlysz** [comment]
Can you attach a screenshoot of the geoscene panel state after the error has been thrown, like this

![image](https://user-images.githubusercontent.com/5639024/71716278-74155480-2e14-11ea-92dd-8ce63e77e236.png)

**Comment by pixeltumbler** [comment]
Will this work?
![blendergis3](https://user-images.githubusercontent.com/59435159/71716875-737dbd80-2e16-11ea-9092-25ab46e45e56.jpg)

**Comment by domlysz** [comment]
Please push the buttons _Geo_ and _Proj_ to see the coordinates of the scene's origin, I suspect the NaN value comes from here

**Comment by pixeltumbler** [comment]
I tried that but got the same error.
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 155, in run
    self.mosaic = self.request()
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 211, in request
    mosaic = self.srv.getImage(self.laykey, bbox, self.zoom, toDstGrid=toDstGrid, outCRS=self.crs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 821, in getImage
    rq = BBoxRequest(tm, bbox, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 298, in __init__
    self.firstCol, self.firstRow = tm.getTileNumber(xmin, ymax, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 232, in getTileNumber
    col = int(math.floor(col))
ValueError: cannot convert float NaN to integer
```
![blendergis4](https://user-images.githubusercontent.com/59435159/71734030-40a1ec80-2e4b-11ea-836d-0cd99a427c97.jpg)

**Comment by domlysz** [comment]
Please can you retry with last version of the addon, it will not solve the issue but will give to me some more clues because I'm not able to reproduce the issue

Install the new version then start blender through a system console. In the addon preferences change the logging level to debug :

![image](https://user-images.githubusercontent.com/5639024/71783503-e8ecb800-2fe7-11ea-9b5d-ddbff7756ee1.png)

Then retry and report to me all messages printed in the system console.

Thanks

**Comment by pixeltumbler** [comment]
Hi, 
I got the following message. 

```
Microsoft Windows [Version 10.0.17763.914]
(c) 2018 Microsoft Corporation. Med ensamrätt.

C:\WINDOWS\system32>cd C:\Program Files\Blender Foundation\Blender 2.81

C:\Program Files\Blender Foundation\Blender 2.81>blender.exe
Read prefs: C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.81\2.81\python
Writing userprefs: 'C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\config\userpref.blend' ok
Info: Deleted 1 object(s)

DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (nan, nan, nan, nan)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:230:Computing tile number x nan y nan z 0 r nan dx nan dy nan
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 155, in run
    self.mosaic = self.request()
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 211, in request
    mosaic = self.srv.getImage(self.laykey, bbox, self.zoom, toDstGrid=toDstGrid, outCRS=self.crs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 822, in getImage
    rq = BBoxRequest(tm, bbox, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 299, in __init__
    self.firstCol, self.firstRow = tm.getTileNumber(xmin, ymax, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 233, in getTileNumber
    col = int(math.floor(col))
ValueError: cannot convert float NaN to integer
```

**Comment by domlysz** [comment]
Can you tell me if it works with Blender 2.80 ?

**Comment by domlysz** [comment]
Can you share to me a screenshoot of the scene's custom properties (after the bug has been raised)

![image](https://user-images.githubusercontent.com/5639024/71784616-90241c00-2ff5-11ea-9318-acbbf064b01f.png)

**Comment by pixeltumbler** [comment]
Sure, here are the screenshot from the custom properties. 
Give me a couple of minutes and will have tried it on blender 2.80
![blendergis5](https://user-images.githubusercontent.com/59435159/71784724-e2197180-2ff6-11ea-9b84-b37997d7a48c.jpg)

**Comment by pixeltumbler** [comment]
Hey! it works in 2.80 :) 
![blendergis6](https://user-images.githubusercontent.com/59435159/71784858-a089c600-2ff8-11ea-87a7-65f72736764f.jpg)

**Comment by domlysz** [comment]
haha making some progress !

Can you download again the addon and run it in debug mode. I've added a new log message, hope to see what's wrong.

**Comment by pixeltumbler** [comment]
There you are. 
```
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (nan, nan, nan, nan)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:230:Computing tile number x nan y nan z 0 r nan dx nan dy nan
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 155, in run
    self.mosaic = self.request()
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 211, in request
    mosaic = self.srv.getImage(self.laykey, bbox, self.zoom, toDstGrid=toDstGrid, outCRS=self.crs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 822, in getImage
    rq = BBoxRequest(tm, bbox, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 299, in __init__
    self.firstCol, self.firstRow = tm.getTileNumber(xmin, ymax, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 233, in getTileNumber
    col = int(math.floor(col))
ValueError: cannot convert float NaN to integer
```

**Comment by pixeltumbler** [comment]
There you go. 
```
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (nan, nan, nan, nan)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:230:Computing tile number x nan y nan z 0 r nan dx nan dy nan
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 155, in run
    self.mosaic = self.request()
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 211, in request
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 822, in getImage
    rq = BBoxRequest(tm, bbox, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 299, in __init__
    self.firstCol, self.firstRow = tm.getTileNumber(xmin, ymax, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 233, in getTileNumber
    col = int(math.floor(col))
ValueError: cannot convert float NaN to integer
```

**Comment by domlysz** [comment]
hum the new message https://github.com/domlysz/BlenderGIS/commit/e46a8e47ab365002a2a09038f703c458deefd1cd is missing, i've you updated the addon ?

**Comment by pixeltumbler** [comment]
Yeah, I downloaded the latest code from here as a zip. Removed the old version and added the new from the downloaded file. But I can't find anything that tells me 
what build it is:
![blendergis7](https://user-images.githubusercontent.com/59435159/71785233-7ab2f000-2ffd-11ea-8ee2-708313ffa99e.jpg)

```
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:184:Computing bounding box w:1586, h:894, vloc:(0.0,0.0,0.0), z:0, r:nan
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:202:Bounding box request : (nan, nan, nan, nan)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:230:Computing tile number x nan y nan z 0 r nan dx nan dy nan
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 155, in run
    self.mosaic = self.request()
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 212, in request
    mosaic = self.srv.getImage(self.laykey, bbox, self.zoom, toDstGrid=toDstGrid, outCRS=self.crs)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 822, in getImage
    rq = BBoxRequest(tm, bbox, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 299, in __init__
    self.firstCol, self.firstRow = tm.getTileNumber(xmin, ymax, zoom)
  File "C:\Users\Mats\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\core\basemaps\mapservice.py", line 233, in getTileNumber
    col = int(math.floor(col))
ValueError: cannot convert float NaN to integer

```

**Comment by domlysz** [comment]
ok I've got my message here :
`Computing bounding box w:1586, h:894, vloc:(0.0,0.0,0.0), z:0, r:nan`

I've found the incriminate function but still don't understand what's wrong in the code and I don't see in Blender 2.81 changelog any update that could explain the issue.

Tomorrow I'll have access to a windows machine, maybe I'll be able to reproduce the issue.

Thanks for your help !

**Comment by pixeltumbler** [comment]
Alright, no worries. I would like to be able to use this on 2.81 so let me know how it turns out.

**Comment by domlysz** [comment]
Still not able to reproduce the issue on Windows.

Can you tell me if it work if you change the projection engine in the addon's preferences from "Auto" to "built in" ?

![image](https://user-images.githubusercontent.com/5639024/71824696-7852a380-309a-11ea-8408-fc0a0eee9b70.png)

**Comment by pixeltumbler** [comment]
And everything works! :)

![blendergis8](https://user-images.githubusercontent.com/59435159/71831148-9e7f4000-30a8-11ea-842c-7f8784a02621.jpg)

**Comment by domlysz** [comment]
great ! so what's the other projection engine available in your drop down list ?? is pyproj or gdal installed on your system ?

**Comment by pixeltumbler** [comment]
epsg.io works. (but is way slower than built in)

**Comment by domlysz** [comment]
ok, finally I'm able to reproduce the issue by updating my system to GDAL3. In fact the issue come from PROJ library used by GDAL to perform reprojection tasks. Since GDAL 3, PROJ has been updated to its version 6 with some importants changes, especially in our use case :

> With PROJ 6, the order of coordinates for EPSG geographic coordinate reference systems is latitude first, longitude second.

https://proj.org/usage/transformation.html

I'll push an update soon to handle this evolution. Thanks for your help

**Comment by pixeltumbler** [comment]
No worries. Thanks for creating the plugin and keeping it updated.

**Comment by domlysz** [comment]
I've make an update https://github.com/domlysz/BlenderGIS/commit/c774fd1270285bf0772a6b4793d19ebf0c0bdd1d but not sure if it works correctly, can you try it ?

**Comment by pixeltumbler** [comment]
Hi, 
Everything seems to work!! 
![blendergis12](https://user-images.githubusercontent.com/59435159/72087322-8e659b80-3308-11ea-94ee-8f5850e4c7da.jpg)

I downloaded the latest version and installed it. 
The only change I made in the preferences was to add the cache folder. 
![blendergis11](https://user-images.githubusercontent.com/59435159/72087499-d7b5eb00-3308-11ea-8f94-7dc9574837a4.jpg)
I made no changes to the settings in the panel or in the popup.
![blendergis13](https://user-images.githubusercontent.com/59435159/72087426-b81ec280-3308-11ea-925a-0c743c3dec4a.jpg)
![blendergis10](https://user-images.githubusercontent.com/59435159/72087438-bb19b300-3308-11ea-8d33-b4ffeae4bf1c.jpg)

**Comment by domlysz** [comment]
Great, and to be sure if you select GDAL as projection engine, everything work ?

**Comment by pixeltumbler** [comment]
Sure, 
![blendergis15](https://user-images.githubusercontent.com/59435159/72088976-7fccb380-330b-11ea-9998-d78a3f4ec1a6.jpg)
And it works.
![blendergis16](https://user-images.githubusercontent.com/59435159/72088993-85c29480-330b-11ea-8294-4aa9d511e039.jpg)

**Comment by domlysz** [comment]
that's great, issue closed ! thanks again !
