### ISSUE TITLE
error  Overpass query failed, ckeck logs for more infos.

### ISSUE THREAD

**Issue by alexeymay** [domlysz/BlenderGIS#237]
Hi thanks for the great product.
I get an error when trying to click on get osm
Overpass query failed, ckeck logs for more infos.
no objects are added
  tried to reinstall Blender, GIS. Does not help .

And in 1/20 cases it turns out to get objects.

I hope you help me

**Comment by domlysz** [comment]
Plase can you report the errror log message printed in the system console

**Comment by alexeymay** [comment]
here is the information from the system console

Read prefs: C:\Users\Alexey\AppData\Roaming\Blender Foundation\Blender\2.81\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender 2.81\2.81\python
╨Ш╨╜╤Д╨╛╤А╨╝╨░╤Ж╨╕╤П: ╨г╨┤╨░╨╗╨╡╨╜╨╛ 1 ╨╛╨▒╤К╨╡╨║╤В(╨╛╨▓)

ERROR:BlenderGIS-master.operators.io_import_osm:668:Overpass query failed
Traceback (most recent call last):
  File "C:\Users\Alexey\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\io_import_osm.py", line 666, in execute
    result = api.query(query)
  File "C:\Users\Alexey\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\lib\osm\overpy\__init__.py", line 72, in query
    f = urlopen(self.url, query)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\urllib\request.py", line 1320, in do_open
    r = h.getresponse()
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\http\client.py", line 1336, in getresponse
    response.begin()
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] ╨г╨┤╨░╨╗╨╡╨╜╨╜╤Л╨╣ ╤Е╨╛╤Б╤В ╨┐╤А╨╕╨╜╤Г╨┤╨╕╤В╨╡╨╗╤М╨╜╨╛ ╤А╨░╨╖╨╛╤А╨▓╨░╨╗ ╤Б╤Г╤Й╨╡╤Б╤В╨▓╤Г╤О╤Й╨╡╨╡ ╨┐╨╛╨┤╨║╨╗╤О╤З╨╡╨╜╨╕╨╡

**Comment by domlysz** [comment]
ConnectionResetError : basically the openstreetmap overpass server hung up, this can be caused by many reasons like server overloaded, temporarily blacklisted IP, query quota exceeded ...

Can't do anything on my side, try to download osm xml data directly from https://www.openstreetmap.org and then import the file through BlenderGIS.

**Comment by alexeymay** [comment]
when loading an OSM file from their site, it gives this error

Read prefs: C:\Users\Alexey\AppData\Roaming\Blender Foundation\Blender\2.81\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender 2.81\2.81\python
╨Ш╨╜╤Д╨╛╤А╨╝╨░╤Ж╨╕╤П: ╨г╨┤╨░╨╗╨╡╨╜╨╛ 1 ╨╛╨▒╤К╨╡╨║╤В(╨╛╨▓)

Traceback (most recent call last):
  File "C:\Users\Alexey\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\io_import_osm.py", line 563, in execute
    result = api.parse_xml(self.filepath)
  File "C:\Users\Alexey\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\lib\osm\overpy\__init__.py", line 161, in parse_xml
    return Result.from_xml(data, api=self)
  File "C:\Users\Alexey\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\lib\osm\overpy\__init__.py", line 298, in from_xml
    data = f.read() #all file in memory
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 749491: character maps to <undefined>

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by domlysz** [comment]
can you share the file to me

**Comment by alexeymay** [comment]
yes of course here he is
[map.zip](https://github.com/domlysz/BlenderGIS/files/4086340/map.zip)

**Comment by domlysz** [comment]
just commit an update to fix this issue : https://github.com/domlysz/BlenderGIS/commit/0c7efff5eebaae84b4d78351fcf57fafaab0a2f6
give it a try

**Comment by alexeymay** [comment]
thanks it works

**Comment by artsandsver** [comment]
Hello I get an error and cant get a map please help me!
bpy.ops.view3d.map_start(dialog="MAP")
bpy.ops.view3d.map_start(src='GOOGLE', grd='WM', lay='SAT', dialog="MAP", query="astana", zoom=10)
bpy.ops.view3d.map_start(src='GOOGLE', grd='WM', lay='SAT', dialog="MAP", query="astana", zoom=14)
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.shade_smooth()
Overpass query failed, ckeck logs for more infos.

**Comment by artsandsver** [comment]
another try was failed ((

bpy.ops.view3d.map_start(dialog="MAP")
bpy.ops.view3d.map_start(src='GOOGLE', grd='WM', lay='SAT', dialog="MAP", query="astana", zoom=10)
bpy.ops.view3d.map_start(src='GOOGLE', grd='WM', lay='SAT', dialog="MAP", query="astana", zoom=14)
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.shade_smooth()
Overpass query failed, ckeck logs for more infos.
bpy.data.window_managers["WinMan"].addon_search = "BlenderGIS"
bpy.context.space_data.params.filename = "bpy.ops.view3d.map_start(dialog=\"MAP\")"
bpy.context.space_data.params.directory = "Загрузки"
bpy.context.space_data.system_folders_active = 2
Modules Installed () from 'W:\\Program Files\\Blender 2.82\\blender-osm-info.zip' into 'C:\\Users\\1\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'
Overpass query failed, ckeck logs for more infos.
Overpass query failed, ckeck logs for more infos.

**Comment by mmv2405** [comment]
Try a different Overpass server: By default, the Blender GIS add-on uses the main Overpass API server. However, there are other Overpass API servers available that you can try. To change the Overpass server, go to the Blender GIS tab, click on the "Settings" button, and then click on the "Overpass" tab. From there, you can select a different server and try the query again.

**Comment by zachas342** [comment]
> 

where's the settings button on the GIS tab?
