### ISSUE TITLE
Import Error -- Reason: image not found

### ISSUE THREAD

**Issue by nateisgood** [domlysz/BlenderGIS#239]
I recently installed BlenderGIS by just dragging the repo into the /addons directory. It appeared in the Add-on menu but when I tried to activate it I got the following error.

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.81/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/nate/Library/Application Support/Blender/2.81/scripts/addons/BlenderGIS-master/__init__.py", line 71, in <module>
    from . import geoscene
  File "/Users/nate/Library/Application Support/Blender/2.81/scripts/addons/BlenderGIS-master/geoscene.py", line 32, in <module>
    from .operators.utils import mouseTo3d
  File "/Users/nate/Library/Application Support/Blender/2.81/scripts/addons/BlenderGIS-master/operators/utils/__init__.py", line 1, in <module>
    from .bgis_utils import placeObj, adjust3Dview, showTextures, addTexture, getBBOX, DropToGround, mouseTo3d, isTopView
  File "/Users/nate/Library/Application Support/Blender/2.81/scripts/addons/BlenderGIS-master/operators/utils/bgis_utils.py", line 7, in <module>
    from ...core import BBOX
  File "/Users/nate/Library/Application Support/Blender/2.81/scripts/addons/BlenderGIS-master/core/__init__.py", line 14, in <module>
    from .basemaps import GRIDS, SOURCES, MapService, GeoPackage, TileMatrix
  File "/Users/nate/Library/Application Support/Blender/2.81/scripts/addons/BlenderGIS-master/core/basemaps/__init__.py", line 2, in <module>
    from .mapservice import MapService, TileMatrix, BBoxRequest, BBoxRequestMZ
  File "/Users/nate/Library/Application Support/Blender/2.81/scripts/addons/BlenderGIS-master/core/basemaps/mapservice.py", line 34, in <module>
    from .gpkg import GeoPackage
  File "/Users/nate/Library/Application Support/Blender/2.81/scripts/addons/BlenderGIS-master/core/basemaps/gpkg.py", line 26, in <module>
    import sqlite3
  File "/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: dlopen(/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-darwin.so, 2): Library not loaded: /Users/azo/Code/blender/blender_build/build-libs/Release/sqlite/lib/libsqlite3.0.dylib
  Referenced from: /Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-darwin.so
  Reason: image not found
```

**Comment by domlysz** [comment]
duplicate #224
