### ISSUE TITLE
I can't enable 3D View: BlenderGIS

### ISSUE THREAD

**Issue by Rohit121l** [domlysz/BlenderGIS#263]
Traceback (most recent call last):
  File "/private/var/folders/7j/5b4s56xx5hvc4fmcx_0yd05r0000gn/T/AppTranslocation/D2EF871A-C5D4-4980-A4C8-8BC53C40F8C3/d/Blender.app/Contents/Resources/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/rohit/Library/Application Support/Blender/2.82/scripts/addons/BlenderGIS-master/__init__.py", line 67, in <module>
    from .core.settings import getSettings, setSettings
  File "/Users/rohit/Library/Application Support/Blender/2.82/scripts/addons/BlenderGIS-master/core/__init__.py", line 14, in <module>
    from .basemaps import GRIDS, SOURCES, MapService, GeoPackage, TileMatrix
  File "/Users/rohit/Library/Application Support/Blender/2.82/scripts/addons/BlenderGIS-master/core/basemaps/__init__.py", line 2, in <module>
    from .mapservice import MapService, TileMatrix, BBoxRequest, BBoxRequestMZ
  File "/Users/rohit/Library/Application Support/Blender/2.82/scripts/addons/BlenderGIS-master/core/basemaps/mapservice.py", line 34, in <module>
    from .gpkg import GeoPackage
  File "/Users/rohit/Library/Application Support/Blender/2.82/scripts/addons/BlenderGIS-master/core/basemaps/gpkg.py", line 26, in <module>
    import sqlite3
  File "/private/var/folders/7j/5b4s56xx5hvc4fmcx_0yd05r0000gn/T/AppTranslocation/D2EF871A-C5D4-4980-A4C8-8BC53C40F8C3/d/Blender.app/Contents/Resources/2.82/python/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/private/var/folders/7j/5b4s56xx5hvc4fmcx_0yd05r0000gn/T/AppTranslocation/D2EF871A-C5D4-4980-A4C8-8BC53C40F8C3/d/Blender.app/Contents/Resources/2.82/python/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: dlopen(/private/var/folders/7j/5b4s56xx5hvc4fmcx_0yd05r0000gn/T/AppTranslocation/D2EF871A-C5D4-4980-A4C8-8BC53C40F8C3/d/Blender.app/Contents/Resources/2.82/python/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-darwin.so, 2): Library not loaded: /Users/azo/Code/blender/blender_build/build-libs/Release/sqlite/lib/libsqlite3.0.dylib
  Referenced from: /private/var/folders/7j/5b4s56xx5hvc4fmcx_0yd05r0000gn/T/AppTranslocation/D2EF871A-C5D4-4980-A4C8-8BC53C40F8C3/d/Blender.app/Contents/Resources/2.82/python/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-darwin.so
  Reason: image not found

**Comment by Rohit121l** [comment]
same error I am facing.

**Comment by domlysz** [comment]
duplicate #224
