### ISSUE TITLE
[Windows] Failing to enable addon, Numpy dll error

### ISSUE THREAD

**Issue by RicoBrase** [domlysz/BlenderGIS#266]
**Blender and OS versions**
- Blender 2.82 (official build)
- Blender 2.83 (latest experimental build, downloaded from Blender homepage a few minutes before opening this issue)
- Windows 10 (1909, Build 18363)
Also see the system information gathered by Blender via Help -> Save System Info:
[system-info.txt](https://github.com/domlysz/BlenderGIS/files/4209744/system-info.txt)

**Describe the bug**

Blender fails to enable the addon. On ticking the Enable checkbox in the Add-On section of the user preferences, the error message below is thrown (and the addon stays disabled).

**Error message**

> Traceback (most recent call last):
  File "C:\Users\Rico Brase\Desktop\blender-2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Rico Brase\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\__init__.py", line 70, in <module>
    from . import prefs
  File "C:\Users\Rico Brase\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\prefs.py", line 11, in <module>
    from .core.proj.reproj import EPSGIO
  File "C:\Users\Rico Brase\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\__init__.py", line 8, in <module>
    from .utils import XY, BBOX
  File "C:\Users\Rico Brase\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\utils\__init__.py", line 3, in <module>
    from .gradient import Color, Stop, Gradient
  File "C:\Users\Rico Brase\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\utils\gradient.py", line 9, in <module>
    from ..maths import akima
  File "C:\Users\Rico Brase\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\maths\akima.py", line 81, in <module>
    import numpy
  File "C:\Users\Rico Brase\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\Rico Brase\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Rico Brase\Desktop\blender-2.83\2.83\python\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung

(The last line is german and translates roughly to: "%1 is not a valid Win32 application")

**How to Reproduce**

1.: Downloaded the Addon
2.: Install it via the addon section of the user preferences dialog
3.: Enable the addon with the checkbox
4.: Error is thrown, addon not enabled.

---

While there are similiar issues, they're all caused by outdated versions of Blender (and/or the issue witch macOS), which is (obviously) not the case here, since I've tried the latest versions of Blender and I'm running Windows.

Fresh Blender installation with no other addons.

**Comment by domlysz** [comment]
it fails on both Blender 2.82 and 2.83 ? Seems loading Numpy module fails. Can you check this : in Blender open the Python console editor and type :
`import Numpy`
If the same error message is raised then the issue come from here and is not related to the addon but to your blender build itself. In this case you can try to reinstall Numpy.

**Comment by RicoBrase** [comment]
@domlysz Thank you for your reply.

The output of the `import numpy` command:

> Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\Rico Brase\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\Rico Brase\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Rico Brase\Desktop\blender-2.83\2.83\python\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung

Seems to be the same error.

I do remember installing numpy via SciPy for some machine learning testing some time ago.

After reinstalling/updating numpy from command line via `pip install --upgrade numpy` (from 1.17.2 to 1.18.1), everything seems to work in both Blender 2.82 and 2.83.

Thank you very much for your help. 😄
