### ISSUE TITLE
Error Get SRTM - "TimeoutError: [WinError 10060]"

### ISSUE THREAD

**Issue by ArcheoPablo** [domlysz/BlenderGIS#269]
I have this error. Can anyone help? 

"Timeout Error: WinError 10060"

https://subefotos.com/ver/?23878567c8ea12c26720281d831f8d1co.jpg

"bpy.ops.view3d.map_start(dialog="MAP")
bpy.ops.object.select_all(action='DESELECT')
Traceback (most recent call last):
  File "C:\Users\apari\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 43, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\apari\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 108, in execute
    with urlopen(rq) as response, open(filePath, 'wb') as outFile:
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\urllib\request.py", line 1320, in do_open
    r = h.getresponse()
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\http\client.py", line 1336, in getresponse
    response.begin()
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
TimeoutError: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder

location: <unknown location>:-1"

**Comment by aarensan** [comment]
Here is a workaround #271

**Comment by domlysz** [comment]
duplicate #271
