### ISSUE TITLE
"ConnectionResetError: [Errno 104] Connection reset by peer"  in Elementary OS

### ISSUE THREAD

**Issue by appym005** [domlysz/BlenderGIS#270]
Blender 2.8 and Elementary OS Hera

Can't get SRTM data.

On clicking Get SRTM, following error is shown:

Traceback (most recent call last):
  File "/home/appy/.config/blender/2.81/scripts/addons/BlenderGIS-master/operators/io_get_srtm.py", line 43, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "/home/appy/.config/blender/2.81/scripts/addons/BlenderGIS-master/operators/io_get_srtm.py", line 108, in execute
    with urlopen(rq) as response, open(filePath, 'wb') as outFile:
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/appy/blnder/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

location: <unknown location>:-1

location: <unknown location>:-1

**How to Reproduce**

Just load a map into edit mode and press "get SRTM"

**Comment by aarensan** [comment]
The http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3&west=-120.168457&south=36.738884&east=-118.465576&north=38.091337&outputFormat=GTiff service is down right now. Hopefully not forever!

**Comment by domlysz** [comment]
duplicate #271
