### ISSUE TITLE
Red 

### ISSUE THREAD

**Issue by himoji** [domlysz/BlenderGIS#279]
2.82 2.83 , Without textures, only red texture
![wtf](https://user-images.githubusercontent.com/61588258/75551538-a206c600-5a5e-11ea-8bc8-d62e4ba7c390.PNG)

**Comment by domlysz** [comment]
This report does not respect the required template. Please make an effort and follow the issue template, no error can be solved without detailed informations, especially error messages.

Nota : the red color means that the images are corrupted in the cache, can't determine why without debug logs

**Comment by domlysz** [comment]
Try to delete the existing cache file (*.gpkg extension file into the cache folder you have specified)

**Comment by geummi1** [comment]
I deleted the cache folder, but there are still red tiles. what can i do to solve this problem?

**Comment by nitish8090** [comment]
Face the same issue.
It says Pillow and PyProj not installed, which weren't installed by default, so I did download pip, pillow and PyProj for python in Blender. Now it detects Pillow in command prompt that opens but still in the log it doesn't detects them. Maybe its due to bevause my office has restricted internet access. I'll try the same at my home PC soon, till them here is a bit of the long log that generates: (can't upload the txt because of "Something went really wrong..." error:

INFO:BlenderGIS-master:92:###### Starting new Blender session : 2020-12-15 12:39:22
DEBUG:BlenderGIS-master.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:31:Pillow unavailable
ERROR:BlenderGIS-master.core.checkdeps:42:Cannot install ImageIO's Freeimage plugin
Traceback (most recent call last):
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\checkdeps.py", line 40, in <module>
    imageio.plugins._freeimage.get_freeimage_lib() #try to download freeimage lib
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\plugins\_freeimage.py", line 54, in get_freeimage_lib
    return get_remote_file('freeimage/' + FNAME_PER_PLATFORM[plat])
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\core\fetching.py", line 98, in get_remote_file
    _fetch_file(url, filename)
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\core\fetching.py", line 154, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'freeimage-3.15.1-win64.dll'. Perhaps there is a no internet connection? If there is, please report this problem.
INFO:BlenderGIS-master:92:###### Starting new Blender session : 2020-12-16 12:59:05
DEBUG:BlenderGIS-master.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:31:Pillow unavailable
ERROR:BlenderGIS-master.core.checkdeps:42:Cannot install ImageIO's Freeimage plugin
Traceback (most recent call last):
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\checkdeps.py", line 40, in <module>
    imageio.plugins._freeimage.get_freeimage_lib() #try to download freeimage lib
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\plugins\_freeimage.py", line 54, in get_freeimage_lib
    return get_remote_file('freeimage/' + FNAME_PER_PLATFORM[plat])
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\core\fetching.py", line 98, in get_remote_file
    _fetch_file(url, filename)
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\core\fetching.py", line 154, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'freeimage-3.15.1-win64.dll'. Perhaps there is a no internet connection? If there is, please report this problem.
INFO:BlenderGIS-master:92:###### Starting new Blender session : 2020-12-23 14:42:45
DEBUG:BlenderGIS-master.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:31:Pillow unavailable
ERROR:BlenderGIS-master.core.checkdeps:42:Cannot install ImageIO's Freeimage plugin
Traceback (most recent call last):
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\checkdeps.py", line 40, in <module>
    imageio.plugins._freeimage.get_freeimage_lib() #try to download freeimage lib
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\plugins\_freeimage.py", line 54, in get_freeimage_lib
    return get_remote_file('freeimage/' + FNAME_PER_PLATFORM[plat])
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\core\fetching.py", line 98, in get_remote_file
    _fetch_file(url, filename)
  File "C:\Users\lenovo1\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\core\fetching.py", line 154, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'freeimage-3.15.1-win64.dll'. Perhaps there is a no internet connection? If there is, please report this problem.

**Comment by leandros-sp** [comment]
I have the same problem and im on win 10 / blender 2.91
I have tryed to delete the blender and the gis and the files and the problem is still there.
In the GIS log it says "ValueError: Could not load bitmap"
Please if anyone can help it would be great.
