### ISSUE TITLE
get OSM error, latitude out of bounds

### ISSUE THREAD

**Issue by sakarimov** [domlysz/BlenderGIS#286]
I used Blender 2.82 on Windows 10
I always get this error when importing OSM:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_import_osm.py", line 669, in execute
    try:
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\lib\osm\overpy\__init__.py", line 119, in query
    msgs=msgs
BlenderGIS-master.operators.lib.osm.overpy.exception.OverpassBadRequest: Error: line 1: static error: Latitudes in bounding boxes must be between -90.0 and 90.0. 

location: <unknown location>:-1

i have googled and find no answer, someone told to change the url in self.url in .../overpy/_init_.py i tried it but no result, thanks for any reply, hope someone help me

**Comment by domlysz** [comment]
seems same issue as #245

**Comment by domlysz** [comment]
must be fixed now https://github.com/domlysz/BlenderGIS/commit/b6861910e5ca567c76785c0cb614fda0dbd40bea

**Comment by sakarimov** [comment]
thanks bro...

Pada tanggal Sel, 10 Mar 2020 pukul 23.56 domlysz <notifications@github.com>
menulis:
