### ISSUE TITLE
Imageio: 'freeimage-3.15.1-win64.dll' was not found on your computer; downloading it now.

### ISSUE THREAD

**Issue by Harrison12315** [domlysz/BlenderGIS#287]
According to the error message， I was missing a file called 'freeimage-3.15.1-win64.dll', but I still reported an error after downloading the file from the Internet and putting it to C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\core\lib\imageio

There is the Log inside Blender：

DEBUG:BlenderGIS-master.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:31:Pillow unavailable
ERROR:BlenderGIS-master.core.checkdeps:42:Cannot install ImageIO's Freeimage plugin
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\core\checkdeps.py", line 40, in <module>
    imageio.plugins._freeimage.get_freeimage_lib() #try to download freeimage lib
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\core\lib\imageio\plugins\_freeimage.py", line 54, in get_freeimage_lib
    return get_remote_file('freeimage/' + FNAME_PER_PLATFORM[plat])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\core\lib\imageio\core\fetching.py", line 98, in get_remote_file
    _fetch_file(url, filename)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\core\lib\imageio\core\fetching.py", line 154, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'freeimage-3.15.1-win64.dll'. Perhaps there is a no internet connection? If there is, please report this problem.

So ,please help the poor child！

**Comment by domlysz** [comment]
in fact you must put the dll into :

Blender\2.82\scripts\addons\BlenderGIS-master\core\lib\imageio\resources\freeimage

(the freeimage subfolder must be created)

**Comment by domlysz** [comment]
duplicate #265
