### ISSUE TITLE
Not getting SRTM

### ISSUE THREAD

**Issue by WatermanMark** [domlysz/BlenderGIS#304]
Because it is my first time using Blender and Blender Gis i am following.
https://youtu.be/Mj7Z1P2hUWk

But when I want to get the SRTM file, i get an error message,

" bpy.context.space_data.system_folders_active = 1
bpy.context.space_data.system_folders_active = 1
bpy.data.window_managers["WinMan"].addon_search = "nod"
bpy.context.space_data.system_folders_active = 1
bpy.context.space_data.system_folders_active = 1
bpy.context.space_data.params.filename = "Test.blend"
bpy.ops.view3d.map_start(dialog="MAP")
bpy.ops.view3d.map_start(src='GOOGLE', grd='WM', lay='SAT', dialog="MAP", query="Bacita Nigeria", zoom=0)
bpy.ops.view3d.map_start(src='GOOGLE', grd='WM', lay='SAT', dialog="MAP", query="Bacita Nigeria", zoom=20)
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
Traceback (most recent call last):
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Unable to open raster, check logs for more infos

location: <unknown location>:-1

bpy.ops.object.select_all(action='DESELECT')
Traceback (most recent call last):
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Unable to open raster, check logs for more infos

location: <unknown location>:-1

bpy.ops.view3d.map_start(dialog="MAP")
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
Traceback (most recent call last):
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Unable to open raster, check logs for more infos

location: <unknown location>:-1

bpy.ops.view3d.map_start(dialog="MAP")
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_all(action='DESELECT')
Traceback (most recent call last):
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Unable to open raster, check logs for more infos

location: <unknown location>:-1 "

Can anyone help me step by step, because I am a beginner.

**Comment by domlysz** [comment]
duplicate #300
