### ISSUE TITLE
Problem with SRTM

### ISSUE THREAD

**Issue by Pasteqq** [domlysz/BlenderGIS#316]
```
bpy.ops.view3d.map_start(dialog="MAP")
bpy.ops.object.select_all(action='DESELECT')
Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  enum "EPSG:4326" not found in ('EPSG:3857')

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  enum "EPSG:4326" not found in ('EPSG:3857')

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  enum "EPSG:4326" not found in ('EPSG:3857')

location: <unknown location>:-1
```
I get that when i try the get srtm try to fix with the differents issues from the other issues but didn't work

**Comment by domlysz** [comment]
sorry it's a side effect of an update I made few hours ago, I've restored the edit, so it should be back to normal now. Please reinstall the addon

**Comment by domlysz** [comment]
also after reinstalling the addon you will have to reset spatial ref system in the addon preferences
![reset](https://user-images.githubusercontent.com/5639024/79669630-281cce80-81bd-11ea-98a2-04063331d1ee.jpg)

**Comment by ppi-com** [comment]
Just downloaded add-on for first time but till getting error with SRT
ERROR:BlenderGIS-master:74:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\Paul\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  enum "EPSG:4326" not found in ('EPSG:3857')
DEBUG:BlenderGIS-master.operators.io_import_osm:672:Requests overpass server : https://lz4.overpass-api.de/api/interpreter
DEBUG:BlenderGIS-master.operators.io_import_osm:675:Overpass query : [out:xml][bbox:51.48822432668231,-0.12084960963780454,51.51557978364669,-0.04394531188528293];(((way[building];);>;););out;
INFO:BlenderGIS-master.operators.io_import_osm:684:Overpass query successful
DEBUG:BlenderGIS-master.operators.io_get_srtm:95:http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3&west=-0.12284960963780454&east=-0.04194531188528293&south=51.486224326682304&north=51.517579783646696&outputFormat=GTiff
ERROR:BlenderGIS-master:74:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  enum "EPSG:4326" not found in ('EPSG:3857')

**Comment by domlysz** [comment]
ok i think it's good this time
57a1033390674eacade1e0c3274f39c80caaa823

**Comment by ppi-com** [comment]
> Thank you! that's working
> [57a1033](https://github.com/domlysz/BlenderGIS/commit/57a1033390674eacade1e0c3274f39c80caaa823)
