### ISSUE TITLE
Pyproj not defined when opening user preference dialog on windows 10

### ISSUE THREAD

**Issue by s-leger** [domlysz/BlenderGIS#34]
Hi, 
When i do open the user prefs dialog to setup a CRS, i get the following error :

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.77\scripts\startup\bl_ui\space_userpref.py", line 1437, in draw
    draw(context)
  File "C:\Users\stephen\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\BlenderGIS-master\prefs.py", line 96, in draw
    elif pyproj:
NameError: name 'pyproj' is not defined

Seem to be a lower case error in pyproj. replace by PYPROJ fix this issue.

**Comment by domlysz** [comment]
Thanks for the pull request !
