### ISSUE TITLE
settings.json become binary containing only zeros

### ISSUE THREAD

**Issue by Begalov** [domlysz/BlenderGIS#347]
# **Blender and OS versions**
Blender 2.83.1 (last worked with Blender 2.82.8) on Windows 10

# **Describe the bug**
After updating to blender 2.83 didn't use the addon, but after update to 2.83.1 seen error followed to settings.json and inside found this:
```
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 
```

Somehow, evidently at rewriting in setSettings function, file was corrupted. 
# **How to Reproduce**

Maybe migrating blender preferences may lead to this kind of bug. 
# **Error message**
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\RUben\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\__init__.py", line 70, in <module>
    from . import prefs
  File "C:\Users\RUben\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\prefs.py", line 11, in <module>
    from .core.proj.reproj import EPSGIO
  File "C:\Users\RUben\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\__init__.py", line 10, in <module>
    from .proj import SRS, Reproj, reprojPt, reprojPts, reprojBbox, reprojImg
  File "C:\Users\RUben\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\proj\__init__.py", line 1, in <module>
    from .srs import SRS
  File "C:\Users\RUben\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\proj\srs.py", line 23, in <module>
    from .srv import EPSGIO
  File "C:\Users\RUben\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\proj\srv.py", line 28, in <module>
    USER_AGENT = getSetting('user_agent')
  File "C:\Users\RUben\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\settings.py", line 22, in getSetting
    prefs = getSettings()
  File "C:\Users\RUben\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\settings.py", line 14, in getSettings
    prefs = json.load(cfg)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

# **Solution**
Replace settings.json with original content:
```
{
	"proj_engine": "AUTO",
	"img_engine": "AUTO",
	"user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
}
```

**Comment by domlysz** [comment]
Thanks for the report, this issue should not appears anymore as, with the last update, the file settings.json is no more rewriten by the addon.
