### ISSUE TITLE
Problem importing DEM file + Can't install GDAL with Python from Blender

### ISSUE THREAD

**Issue by leonardofmed** [domlysz/BlenderGIS#351]
Using Blender v2.83.1 and Win10

Although "Successfully installed GDAL-3.1.1" message appears, no "osgeo" or "gdal" folders are created. I followed the instructions from wiki and no other Python exist in PATH. I see that this [issue](https://github.com/domlysz/BlenderGIS/issues/250) has the same problem, but I didn't understood the solution provided by the user:

> I could solve my trouble I set up only a new cache folder in the Plugin setup, and the issue doest appears anymore.

_Originally posted by @daniloulf in https://github.com/domlysz/BlenderGIS/issues/250#issuecomment-586349664_

--- 

**Why I'm trying to install it?**

I'm trying to create a 3D model using a DEM and a raster, I believe that I used to do this without GDAL in previous versions, but now it seems required to have.

I'm using a georeferenced PNG file as raster (160MB) and opening as 'Basemap on new plane'. Everything OK so far. Then I tried to open a DEM (.tif | 240MB) using the option 'DEM as displacement texture', using the previous loaded object with the option 'Apply on existing mesh'. 

The following error appeared: 

```
Traceback (most recent call last):
  File "C:\Users\Leonardo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\operators\io_import_georaster.py", line 384, in execute
    grid = bpyGeoRaster(filePath, subBoxGeo=subBox, clip=self.clip, fillNodata=self.fillNodata, useGDAL=HAS_GDAL, raw=True)
  File "C:\Users\Leonardo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\operators\utils\georaster_utils.py", line 223, in __init__
    GeoRaster.__init__(self, path, subBoxGeo=subBoxGeo, useGDAL=useGDAL)
  File "C:\Users\Leonardo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\georaster\georaster.py", line 69, in __init__
    self._fromTIFF()
  File "C:\Users\Leonardo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\georaster\georaster.py", line 125, in _fromTIFF
    tif = Tyf.open(self.path)[0]
  File "C:\Users\Leonardo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\lib\Tyf\__init__.py", line 479, in open
    elif first in [0x4d4d, 0x4949]: obj = TiffFile(fileobj)
  File "C:\Users\Leonardo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\lib\Tyf\__init__.py", line 310, in __init__
    next_ifd = from_buffer(i, fileobj, next_ifd, byteorder)
  File "C:\Users\Leonardo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\lib\Tyf\__init__.py", line 99, in from_buffer
    _read_IFD(obj, fileobj, offset, byteorder)
  File "C:\Users\Leonardo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\lib\Tyf\__init__.py", line 83, in _read_IFD
    else: tt.value = unpack(fmt, fileobj)
  File "C:\Users\Leonardo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\core\lib\Tyf\__init__.py", line 11, in <lambda>
    unpack = lambda fmt, fileobj: struct.unpack(fmt, fileobj.read(struct.calcsize(fmt)))
struct.error: unpack requires a buffer of 4 bytes

location: <unknown location>:-1

location: <unknown location>:-1
```

If  try to import the DEM as 'DEM raw data build [slow]' I get a similar error.

---

From the [wiki](https://github.com/domlysz/BlenderGIS/wiki/Import-DEM-grid#import-with-gdal) I see that this options should work without GDAL, so I imagine that the problem is caused by another reason. I tried with both DEM import options and tried to modify the operator options with all the options provided, the same problem persist.

I also tried to modify the format of the DEM to PNG and got a different error: 
```
ERROR:BlenderGIS-master:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\Leonardo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\operators\io_import_georaster.py", line 454, in execute
    mesh = exportAsMesh(grid, dx, dy, self.step, reproj=rprjToScene, subset=self.clip, flat=False, buildFaces=self.buildFaces)
  File "C:\Users\Leonardo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\operators\utils\georaster_utils.py", line 117, in exportAsMesh
    if z == georaster.noData:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by leonardofmed** [comment]
It seems that there was a problem recognizing the original DEM file, after exporting the same file to the same format through QGIS the workflow "Basemap as new plane" and then "DEM as displacement texture" worked. The other option "DEM raw data build" don't seem to work, it loading for a long time until it crashes when no more memory is available, look like there is some kind of memory leak.

**Comment by leonardofmed** [comment]
> 
> 
> It seems that there was a problem recognizing the original DEM file, after exporting the same file to the same format through QGIS the workflow "Basemap as new plane" and then "DEM as displacement texture" worked. The other option "DEM raw data build" don't seem to work, it loading for a long time until it crashes when no more memory is available, look like there is some kind of memory leak.

Problem fixed by increasing the number of steps
