### ISSUE TITLE
Blender GIS MASTER 3D Add On Error with SRTM 

### ISSUE THREAD

**Issue by GianniDeliu** [domlysz/BlenderGIS#397]
I was making a 3d plan and i wanted to use the srtm function but gave me this error
Traceback (most recent call last):
  File "C:\Users\Gaia\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\Gaia\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 199, in _call_
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Errore: Unable to open raster, check logs for more infos

location: <unknown location>:-1

**Comment by domlysz** [comment]
Related to #382 Please update the addon.
