### ISSUE TITLE
SRTM issue

### ISSUE THREAD

**Issue by unity2k** [domlysz/BlenderGIS#410]
# **Blender and OS versions**

Blender 2.92 Alpha on Windows 10 -- I also tried this on 2.91 beta with the same results

# **Describe the bug**

Trying to grab the SRTM data produces the following error message: 

Python: Traceback (most recent call last):
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\ZenUV\operators\operators.py", line 867, in execute
    if checker_setup.switch_checker(obj):
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\ZenUV\utils\checker_setup.py", line 97, in switch_checker
    if mat.use_nodes:
AttributeError: 'NoneType' object has no attribute 'use_nodes'

location: <unknown location

. -->

# **How to Reproduce**

Simply run BlenderGIS on the current daily build of 2.92

# **Error message**

**Comment by domlysz** [comment]
looks like the issue come from the Zen-UV addon...

**Comment by nathandloper** [comment]
I'm also receiving the error.  SRTM data is not available when making the query.

**Comment by unity2k** [comment]
@domlysz Maybe I wasn't paying the best of attention as that was a different error I'd had with that addon (now resolved with 2.92) so I checked again and the message is the same and will be correctly pasted this time. My apologies for the sloppy reporting.

Python: Traceback (most recent call last):
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlenderGIS\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlenderGIS\operators\io_get_srtm.py", line 108, in execute
    with urlopen(rq) as response, open(filePath, 'wb') as outFile:
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\urllib\request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\urllib\request.py", line 1322, in do_open
    r = h.getresponse()
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Blender Foundation\Blender\2.92\python\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

location: <unknown location>:-1

**Comment by unity2k** [comment]
None of my bug report is relevant as things work perfectly in 2.90 so I'm closing this issue until 2.92 is further along.
