### ISSUE TITLE
fail to enable in blender 2.77

### ISSUE THREAD

**Issue by maclaud** [domlysz/BlenderGIS#43]
Hello 
i  can install the addon without any problems but when i try to enable it blender complain about  numpy, i copy the traceback bellow
its only ocuur in blender 2.77 
in blender 2.74 it work like a charm
tnaks Claudio
Traceback (most recent call last):
  File "/usr/share/blender/2.77/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/home/claudio/.config/blender/2.77/scripts/addons/BlenderGIS-master/__init__.py", line 43, in <module>
    from .basemaps import mapviewer
  File "/home/claudio/.config/blender/2.77/scripts/addons/BlenderGIS-master/basemaps/mapviewer.py", line 36, in <module>
    from .mapservice import MapService, PILLOW
  File "/home/claudio/.config/blender/2.77/scripts/addons/BlenderGIS-master/basemaps/mapservice.py", line 41, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

**Comment by domlysz** [comment]
hi,
I facing the same problem, it's because 2.77 use Python 3.5 and your numpy version in python3/dist-packages is building for Python 3.4, it's really a mess to update libs for py3.5 so finally I reinstalled newer version of my system !

**Comment by maclaud** [comment]
thanks for the update and for your work
