### ISSUE TITLE
BIGTIFF support for georeferenced Raster

### ISSUE THREAD

**Issue by janausis** [domlysz/BlenderGIS#435]
# **Blender and OS versions**

Windows 10 20H2, Blender: 2.91.0
# **Describe the bug**

I can't open BIGTIFF files as georeferenced Raster. Is BIGTIFF in any way supported or not and how could i get it to work?
In the file BlenderGIS/core/basemaps/mapservice.py/ there are some mentions of BIGTIFFs which seem to indicate BIGTIFFs can be loaded, but I couldn't get it to work.
If it doesn't work with BIGTIFF, is there any other way to load a ~8GB File as a Raster?

# **How to Reproduce**

Load a BIGTIFF as Georef Raster

# **Error message**

```
DEBUG:BlenderGIS-225.core.proj.srv:Search crs : http://epsg.io/?q=32623&format=json
DEBUG:BlenderGIS-225.core.proj.srv:Search results : [('32623', 'WGS 84 / UTM zone 23N')]
ERROR:BlenderGIS-225.operators.io_import_georaster:Unable to open raster
Traceback (most recent call last):
  File "C:\Users\ronso\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-225\operators\io_import_georaster.py", line 257, in execute
    rast = bpyGeoRaster(filePath)
  File "C:\Users\ronso\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-225\operators\utils\georaster_utils.py", line 223, in __init__
    GeoRaster.__init__(self, path, subBoxGeo=subBoxGeo, useGDAL=useGDAL)
  File "C:\Users\ronso\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-225\core\georaster\georaster.py", line 69, in __init__
    self._fromTIFF()
  File "C:\Users\ronso\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-225\core\georaster\georaster.py", line 125, in _fromTIFF
    tif = Tyf.open(self.path)[0]
  File "C:\Users\ronso\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-225\core\lib\Tyf\__init__.py", line 479, in open
    elif first in [0x4d4d, 0x4949]: obj = TiffFile(fileobj)
  File "C:\Users\ronso\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-225\core\lib\Tyf\__init__.py", line 299, in __init__
    raise IOError("BigTIFF file not supported")
OSError: BigTIFF file not supported
```

**Comment by domlysz** [comment]
Blender itself cannot read bigtiff files. Even if this format was supported, Blender is not designed to read very large file in a memory friendly way.
