### ISSUE TITLE
I can't import buildings from OSM

### ISSUE THREAD

**Issue by jsj2311** [domlysz/BlenderGIS#439]
# **Blender and OS versions**

Blender 2.91.0 and Windows 10.

# **Describe the bug**

When I try to import constructions from the OSM web it shows an error.

# **How to Reproduce**

When I click on get OSM and ways and building the error message appears in the image.
![Sem título](https://user-images.githubusercontent.com/77174787/106968667-0e3a8100-6728-11eb-8dbe-a72566bc3cd1.png)

# **Error message**

this is the error log:

Python: Traceback (most recent call last):
  File "C:\Users\josel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\operators\io_import_osm.py", line 673, in execute
    result = api.query(query)
  File "C:\Users\josel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\operators\lib\osm\overpy\__init__.py", line 106, in query
    raise exception.OverpassUnknownContentType(content_type)
BlenderGIS-master.operators.lib.osm.overpy.exception.OverpassUnknownContentType: Unknown content type: text/html; charset=utf-8

location: <unknown location>:-1

**Comment by domlysz** [comment]
What's the location ?

**Comment by jsj2311** [comment]
The location is in the city of Paraty in Brazil, but I tested it in other cities too and it gave the same error.

**Comment by jsj2311** [comment]
the problem continues for any location I select :(

**Comment by jsj2311** [comment]
uninstalled Blender 2.91.0 and installed 2.83.12 and returned to working normally :D

**Comment by domlysz** [comment]
thank you for the feedback, it might help if you can test various Blender versions from 2.83 and 2.91 and tell me which one break the addon. I can't reproduce the issue on my side that's why I don't know what to say, I suspect some countries block requests to the osm overpass server

**Comment by jsj2311** [comment]
I'll try. If it is really a request block due to the IP being Brazilian, would it be the case of modifying the IP for another country?

**Comment by raghav0303** [comment]
I am facing the same issue.

**Comment by LV2021** [comment]
I am having the same issue. and I am using version 3.5.    SOSOS I need help please
