### ISSUE TITLE
importing georeferenced .tif DEM into Blender

### ISSUE THREAD

**Issue by goosebessie** [domlysz/BlenderGIS#448]
# **Blender and OS versions**

<Blender 2.91.2 and Windows 10>

# **Describe the bug**

<FYI, I am new to Blender.  BlenderGIS gives error when I try to import drone produced georeferenced Structure from Motion DEM .tif-->

# **How to Reproduce**

<-- 1. Click on GIS tab   2. import georeferenced raster   3. choose .tif file      4. Mode: DEM as Displacement texture.    5. Choose correct scene georeferencing.   6. import georaster    7. receive error--
![image](https://user-images.githubusercontent.com/79538907/108894592-77ebd380-75e0-11eb-89a7-beeec1431b83.png)
>

# **Error message**

<Python: Traceback (most recent call last): File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\operators\io_import_georaster.py", line 445, in execute grid = GeoRaster(filePath, subBoxGeo=subBox, useGDAL=HAS_GDAL) File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\georaster\georaster.py", line 69, in init self.fromTIFF() File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\georaster\georaster.py", line 125, in fromTIFF tif = Tyf.open(self.path)[0] File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\Tyf_init.py", line 479, in open elif first in [0x4d4d, 0x4949]: obj = TiffFile(fileobj) File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\Tyf_init.py", line 310, in init next_ifd = from_buffer(i, fileobj, next_ifd, byteorder) File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\Tyf_init_.py", line 99, in from_buffer read_IFD(obj, fileobj, offset, byteorder) File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\Tyf_init.py", line 83, in read_IFD else: tt.value = unpack(fmt, fileobj) File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\Tyf_init.py", line 11, in unpack = lambda fmt, fileobj: struct.unpack(fmt, fileobj.read(struct.calcsize(fmt))) struct.error: unpack requires a buffer of 4 bytes location: :-1>

**Comment by domlysz** [comment]
you can try to open the file in qgis and re-export it to a new tif, sometimes it solve these kind of issue
#405

**Comment by JPAbdalla** [comment]
I got the same issue and same error messages. I'm going to try the answer from domlysz.

**Comment by 12stations** [comment]
Hi all. I am experiencing the same issue… As an unexperienced Blender user, I am not sure if the error is exactly the same (see image.) I also exported it again form QGIS, and also changed the file's projection to metric with the same unsuccessful output. Any other leads? Thanks.

![Error message](https://user-images.githubusercontent.com/81698228/113170828-d559ec80-923e-11eb-8794-4ac7995c11d3.png)

**Comment by domlysz** [comment]
@12stations can you share the file ?
