### ISSUE TITLE
M1 Mac Blender 2.93 

### ISSUE THREAD

**Issue by Keeneori** [domlysz/BlenderGIS#501]
# **I am using Blender 2.93 on M1 Mac  **

# **None of the basemap/elevation data will load. It just goes idle after attempting to add **

# **How to Reproduce**

# **Error message**

**Comment by dsward2** [comment]
I've got a similar problem on my M1 Mac and Blender 2.93.1 - but I got a window with the error messages pasted below.  gdal is installed with MacPorts at /opt/local/lib - in the Mac's system path, but I'm not sure if the Python environment bundled in Blender is looking there.  I loaded an OpenStreetMap export file to define the location.

The ~/.bgis directory contains two files -

bgis.log
GOOGLE_SAT_WM.gpkg

Here is the relevant portion of bgis.log when attempting to download the elevation data -

DEBUG:BlenderGIS-master.operators.io_get_dem:103:https://portal.opentopography.org/API/globaldem?demtype=SRTMGL1&west=-92.96237460587611&east=-92.858273912316&south=35.091570302688545&north=35.13370518098602&outputFormat=GTiff
ERROR:BlenderGIS-master:96:Uncaught exception
Traceback (most recent call last):
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/operators/io_import_georaster.py", line 387, in execute
    grid = bpyGeoRaster(filePath, subBoxGeo=subBox, clip=self.clip, fillNodata=self.fillNodata, useGDAL=HAS_GDAL, raw=True)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/operators/utils/georaster_utils.py", line 239, in __init__
    img = self.readAsNpArray()
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/georaster/georaster.py", line 253, in readAsNpArray
    img = NpImage(self.path, subBoxPx=self.subBoxPx, noData=self.noData, georef=self.georef, adjustGeoref=True)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/georaster/npimg.py", line 127, in __init__
    self.data = self._npFromPath(data)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/georaster/npimg.py", line 227, in _npFromPath
    return self._npFromImgIO(path)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/georaster/npimg.py", line 258, in _npFromImgIO
    data = imageio.imread(img)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/lib/imageio/core/functions.py", line 181, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/lib/imageio/core/functions.py", line 107, in get_reader
    raise ValueError('Could not find a format to read the specified file '
ValueError: Could not find a format to read the specified file in mode 'i'
ERROR:BlenderGIS-master:96:Uncaught exception
Traceback (most recent call last):
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/operators/io_get_dem.py", line 140, in execute
    bpy.ops.importgis.georaster(
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/bpy/ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/operators/io_import_georaster.py", line 387, in execute
    grid = bpyGeoRaster(filePath, subBoxGeo=subBox, clip=self.clip, fillNodata=self.fillNodata, useGDAL=HAS_GDAL, raw=True)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/operators/utils/georaster_utils.py", line 239, in __init__
    img = self.readAsNpArray()
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/georaster/georaster.py", line 253, in readAsNpArray
    img = NpImage(self.path, subBoxPx=self.subBoxPx, noData=self.noData, georef=self.georef, adjustGeoref=True)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/georaster/npimg.py", line 127, in __init__
    self.data = self._npFromPath(data)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/georaster/npimg.py", line 227, in _npFromPath
    return self._npFromImgIO(path)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/georaster/npimg.py", line 258, in _npFromImgIO
    data = imageio.imread(img)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/lib/imageio/core/functions.py", line 181, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/Volumes/ExternalSSD/Users/dsward/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/core/lib/imageio/core/functions.py", line 107, in get_reader
    raise ValueError('Could not find a format to read the specified file '
ValueError: Could not find a format to read the specified file in mode 'i'

location: /Applications/Blender.app/Contents/Resources/2.93/scripts/modules/bpy/ops.py:130

**Comment by dsward2** [comment]
Apple released macOS Big Sur 11.5 today, and it seems to fix the problems with Basemap and Get Elevation in the BlenderGIS addon.

**Comment by somcsongor** [comment]
I have the same issues on my M1 MacBook pro under macOS 11.6. My blender version is 2.93.3.

This is what blender says when I'm trying to import google maps satellite data:

bpy.ops.view3d.map_start(dialog="MAP")
Python: Traceback (most recent call last):
  File "/Users/user_name/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/operators/view3d_mapviewer.py", line 792, in modal
    loc1 = mouseTo3d(context, self.x1, self.y1)
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/bpy_types.py", line 728, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OT_map_viewer' object has no attribute 'x1'

location: <unknown location>:-1

**Comment by bvkNL** [comment]
This seems to be an issue with BlenderGIS using FreeImage through imageIO, which only has an x86 library available.

I fixed this by installing the ARM version of FreeImage through MacPorts: https://ports.macports.org/port/freeimage/ and restarting Blender.

**Comment by bchoi** [comment]
I use [Homebrew](https://brew.sh/) and it installs arm64 library under `/opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage.dylib`. It looks like there is a way to manually set the freeimage library via environment variable (https://github.com/domlysz/BlenderGIS/blob/master/core/lib/imageio/plugins/_freeimage.py#L45).

bash> IMAGEIO_FREEIMAGE_LIB=/opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage.dylib /Applications/Blender.app/Contents/MacOS/Blender

**Comment by dsward2** [comment]
The installation of FreeImage with MacPorts fixed the problem here, thanks for the info.
