### ISSUE TITLE
Displacement modifier issues

### ISSUE THREAD

**Issue by WGPROD** [domlysz/BlenderGIS#565]
# **Blender and OS versions**

# **Describe the bug**

When I close a saved file and reopen, the displacement modifyer on my map gets.. displaced out of their original values.  Also happens when adding a bezier curve to the project.  

# **How to Reproduce**

 I have two maps in one file, a larger low rez and a higher rez one in the midle.  The larger map has a bollean modifier (substract) on a wire cube solid so that I can see only the high rez map in the middle.  Both maps are zoomed in at about level 16 

# **Error message**

This is the error message when I try to re-import the elevation data for the map by deleting the displacement modifier and re-creating it, but by now the elevation data is already all over the place.  Maybe I should just stick to one map, but its pretty cool to have a gradation of detail in the horizon with several ones.  Anyway thanks great plugin.  

Python: Traceback (most recent call last):
  File "/Users/---username--Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/operators/io_get_dem.py", line 140, in execute
    bpy.ops.importgis.georaster(
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/bpy/ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/thomaswadham-gagnon/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/operators/io_import_georaster.py", line 414, in execute
    geoRastUVmap(obj, uvTxtLayer, grid, dx, dy, reproj=rprjToRaster)
  File "/Users/thomaswadham-gagnon/Library/Application Support/Blender/2.93/scripts/addons/BlenderGIS-master/operators/utils/georaster_utils.py", line 181, in geoRastUVmap
    uvLayer.data[i].uv = [u,v]
AttributeError: 'NoneType' object has no attribute 'data'

location: /Applications/Blender.app/Contents/Resources/2.93/scripts/modules/bpy/ops.py:130

location: <unknown location>:-1

**Comment by WGPROD** [comment]
Ok issues seem to be resolved by only making one map.  The texture map is saved in the cache folder and every time you create a new map it crushes the previous texture, effectively displacing the new map.   So no solution in the short term for multiple maps..
