### ISSUE TITLE
Basemap is not loading due to an error

### ISSUE THREAD

**Issue by pl4sma2389** [domlysz/BlenderGIS#570]
# **Blender and OS versions**
Windows 10 Home
Blender 2.93.5

# **Describe the bug**
Blender fails to load the basemap. This may or may not be an error with my installation, but I'm not sure what it is and I have no idea how to fix it. I have tried reinstalling BlenderGIS.

# **How to Reproduce**
Open a new file in Blender. Delete the default collection and objects. Click on Basemap.

# **Error message**
```
DEBUG:BlenderGIS-225.core.checkdeps:GDAL Python binding available
DEBUG:BlenderGIS-225.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-225.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-225.core.checkdeps:ImageIO Freeimage plugin available
DEBUG:BlenderGIS-225.operators.view3d_mapviewer:Bounding box request : (-124060354.38797247, -74749298.70063956, 124060354.38797247, 74749298.70063956)
DEBUG:BlenderGIS-225.core.basemaps.mapservice:35 tiles requested, 1 already in cache, 34 remains to download
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\__init__.py", line 95, in _excepthook
    if 'BlenderGIS' in exc_traceback.tb_frame.f_code.co_filename:
AttributeError: 'NoneType' object has no attribute 'tb_frame'

Original exception was:
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ERROR:BlenderGIS-225.core.basemaps.mapservice:Corrupted tile on cache
Traceback (most recent call last):
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\core\basemaps\mapservice.py", line 881, in getImage
    img = NpImage(data)
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\core\georaster\npimg.py", line 122, in __init__
    self.data = self._npFromBLOB(data)
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\core\georaster\npimg.py", line 250, in _npFromBLOB
    data = self._npFromGDAL(ds)
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\core\georaster\npimg.py", line 277, in _npFromGDAL
    data = ds.ReadAsArray()
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\osgeo\gdal.py", line 2496, in ReadAsArray
    from osgeo import gdal_array
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\osgeo\gdal_array.py", line 35, in <module>
    _gdal_array = swig_import_helper()
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\osgeo\gdal_array.py", line 30, in swig_import_helper
    _mod = imp.load_module('_gdal_array', fp, pathname, description)
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: numpy.core.multiarray failed to import
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\__init__.py", line 95, in _excepthook
    if 'BlenderGIS' in exc_traceback.tb_frame.f_code.co_filename:
AttributeError: 'NoneType' object has no attribute 'tb_frame'

Original exception was:
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ERROR:BlenderGIS-225:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\__init__.py", line 117, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\operators\view3d_mapviewer.py", line 158, in run
    self.mosaic.save(self.imgPath)
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\core\georaster\npimg.py", line 407, in save
    mem = self.toGDAL()
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\core\georaster\npimg.py", line 358, in toGDAL
    mem.GetRasterBand(bandIdx+1).WriteArray(bandArray)
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\osgeo\gdal.py", line 3975, in WriteArray
    from osgeo import gdal_array
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\osgeo\gdal_array.py", line 35, in <module>
    _gdal_array = swig_import_helper()
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\osgeo\gdal_array.py", line 30, in swig_import_helper
    _mod = imp.load_module('_gdal_array', fp, pathname, description)
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\__init__.py", line 117, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\operators\view3d_mapviewer.py", line 158, in run
    self.mosaic.save(self.imgPath)
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\core\georaster\npimg.py", line 407, in save
    mem = self.toGDAL()
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlenderGIS-225\core\georaster\npimg.py", line 358, in toGDAL
    mem.GetRasterBand(bandIdx+1).WriteArray(bandArray)
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\osgeo\gdal.py", line 3975, in WriteArray
    from osgeo import gdal_array
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\osgeo\gdal_array.py", line 35, in <module>
    _gdal_array = swig_import_helper()
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\osgeo\gdal_array.py", line 30, in swig_import_helper
    _mod = imp.load_module('_gdal_array', fp, pathname, description)
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "S:\Alt Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: numpy.core.multiarray failed to import
```

**Comment by pl4sma2389** [comment]
I managed to fix it by installing the latest versions of GDAL and numpy manually.
