### ISSUE TITLE
import osm error

### ISSUE THREAD

**Issue by kennizy** [domlysz/BlenderGIS#576]
Traceback (most recent call last):
  File "C:\Users\zhengying\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS\operators\io_import_osm.py", line 592, in execute
    self.build(context, result, geoscn.crs)
  File "C:\Users\zhengying\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS\operators\io_import_osm.py", line 443, in build
    seed(way.id, way.tags, pts)
  File "C:\Users\zhengying\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS\operators\io_import_osm.py", line 251, in seed
    face = bm.faces.new(verts)
TypeError: faces.new(...): sequence incorrect size, expected [3 - -1], given 2

location: <unknown location>:-1

**Comment by wsxue** [comment]
I have the same problem， Did you solve it? please
