### ISSUE TITLE
OSM data won't load anymore

### ISSUE THREAD

**Issue by MrWulf81** [domlysz/BlenderGIS#622]
# **Blender and OS versions**

Blender: 3.0
OS: Windows 10 (Build 19043.1526)

# **Describe the bug**

When I try to import osm data from a region I only get an error message. It doesn't matter which dataset I want to import every option produces the same error message (aside from the query). 

# **How to Reproduce**

1. Click on GIS->Web geodata->Get OSM to open the settings dialog while the map is selected in objectmode
2. Select any of the Settings (e.g. under "Nodes" the "building", with no Elevation from object / separate objects and with buildings extrusion )
3. Click on OK and after a second or so I get an error message

# **Error message**

DEBUG:BlenderGIS-master.operators.io_import_osm:670:Overpass query : [out:xml][bbox:34.37857917679976,134.03388976801298,34.409742182989795,134.05723572118453];(node[building];);out;
ERROR:BlenderGIS-master:96:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\xxxxxxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderGIS-master\operators\io_import_osm.py", line 673, in execute
    result = api.query(query)
  File "C:\Users\xxxxxxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderGIS-master\operators\lib\osm\overpy\__init__.py", line 106, in query
    raise exception.OverpassUnknownContentType(content_type)
BlenderGIS-master.operators.lib.osm.overpy.exception.OverpassUnknownContentType: Unknown content type: text/html; charset=UTF-8

**Comment by siukeiyu** [comment]
I have the same trouble

**Comment by FrikkieRSA** [comment]
I'm having the same problem.
