### ISSUE TITLE
Unknown location error, while exporting shape-files

### ISSUE THREAD

**Issue by Josefen** [domlysz/BlenderGIS#642]
# **Blender and OS versions**

Blender 3.0.0, Windows 10 Enterprise, 19042.1586

# **Describe the bug**

When exporting to .shp I get error:  'location: unknown location:-1'
The result is an empty file.

# **How to Reproduce**

Don't know.

# **Error message**

Python: Exception ignored in: <function Writer.__del__ at 0x000001D5B50DC1F0>
Traceback (most recent call last):
  File "C:\Users\bkjosrun\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderGIS-master\core\lib\shapefile.py", line 1104, in __del__    self.close()
  File "C:\Users\bkjosrun\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderGIS-master\core\lib\shapefile.py", line 1125, in close    self.__shapefileHeader(self.shp, headerType='shp')
  File "C:\Users\bkjosrun\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderGIS-master\core\lib\shapefile.py", line 1299, in __shapefileHeader  f.write(pack("<4d", zbox[0], zbox[1], mbox[0], mbox[1]))
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\bkjosrun\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderGIS-master\operators\io_export_shp.py", line 171, in execute
    bm.from_object(obj, context.evaluated_depsgraph_get(), deform=True) #'deform' allows to consider modifier deformation
TypeError: 'deform' is an invalid keyword argument for from_object()

location: unknown location:-1

**Comment by Hareden** [comment]
is it ok now? how can we solve it?

**Comment by Josefen** [comment]
> 

It works in 2.98, but not in 3.1.
Get the location: unknown location:-1 error

**Comment by Hareden** [comment]
> > 
> 
> It works in 2.98, but not in 3.1. Get the location: unknown location:-1 error

sure! the same problem!it is the Blender 3.0 compatibility issue : can't export shapefile;
we should wait  for the better  code library!
