### ISSUE TITLE
给高程数据添加了个API，加载了一下就成这了，请问是什么原因

### ISSUE THREAD

**Issue by LN0821** [domlysz/BlenderGIS#656]
Python: Traceback (most recent call last):
  File "/Users/mac/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-master/operators/io_get_dem.py", line 140, in execute
    bpy.ops.importgis.georaster(
  File "/Applications/Blender.app/Contents/Resources/3.1/scripts/modules/bpy/ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: 错误: Python: Traceback (most recent call last):
  File "/Users/mac/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-master/operators/io_import_georaster.py", line 387, in execute
    grid = bpyGeoRaster(filePath, subBoxGeo=subBox, clip=self.clip, fillNodata=self.fillNodata, useGDAL=HAS_GDAL, raw=True)
  File "/Users/mac/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-master/operators/utils/georaster_utils.py", line 239, in __init__
    img = self.readAsNpArray()
  File "/Users/mac/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-master/core/georaster/georaster.py", line 253, in readAsNpArray
    img = NpImage(self.path, subBoxPx=self.subBoxPx, noData=self.noData, georef=self.georef, adjustGeoref=True)
  File "/Users/mac/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-master/core/georaster/npimg.py", line 127, in __init__
    self.data = self._npFromPath(data)
  File "/Users/mac/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-master/core/georaster/npimg.py", line 227, in _npFromPath
    return self._npFromImgIO(path)
  File "/Users/mac/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-master/core/georaster/npimg.py", line 258, in _npFromImgIO
    data = imageio.imread(img)
  File "/Users/mac/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-master/core/lib/imageio/core/functions.py", line 181, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/Users/mac/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-master/core/lib/imageio/core/functions.py", line 107, in get_reader
    raise ValueError('Could not find a format to read the specified file '
ValueError: Could not find a format to read the specified file in mode 'i'

location: /Applications/Blender.app/Contents/Resources/3.1/scripts/modules/bpy/ops.py:130

location: <unknown location>:-1

**Comment by aplr** [comment]
See my answer on #655
