### ISSUE TITLE
Mac OS

### ISSUE THREAD

**Issue by Gifted0ne** [domlysz/BlenderGIS#664]
will this addon work on mac OS. tried loading it but getting error. can download it but it does not want to activate

**Comment by awill1988** [comment]
works on my computer

**Comment by PixelPartner** [comment]
I tried on macOS 12.4 (M1 SoC) with Blender 3.1.2 and had nothing but trouble:

Here the head of the Log file:
INFO:BlenderGIS-225:92:###### Starting new Blender session : 2022-05-19 11:06:34
DEBUG:BlenderGIS-225.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-225.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-225.core.checkdeps:31:Pillow unavailable
DEBUG:BlenderGIS-225.core.checkdeps:46:ImageIO Freeimage plugin available
DEBUG:BlenderGIS-225.operators.view3d_mapviewer:201:Bounding box request : (-165544258.37890333, -91342860.29701191, 165544258.37890333, 91342860.29701191)
DEBUG:BlenderGIS-225.core.basemaps.mapservice:724:45 tiles requested, 0 already in cache, 45 remains to download
DEBUG:BlenderGIS-225.core.basemaps.mapservice:578:https://tile.openstreetmap.org/0/0/0.png
ERROR:BlenderGIS-225.core.basemaps.mapservice:883:Corrupted tile on cache
Traceback (most recent call last):
  File "/Users/tkumlehn/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-225/core/basemaps/mapservice.py", line 881, in getImage
    img = NpImage(data)
  File "/Users/tkumlehn/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-225/core/georaster/npimg.py", line 122, in __init__
    self.data = self._npFromBLOB(data)
  File "/Users/tkumlehn/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-225/core/georaster/npimg.py", line 242, in _npFromBLOB
    data = self._npFromImgIO(img)
  File "/Users/tkumlehn/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-225/core/georaster/npimg.py", line 258, in _npFromImgIO
    data = imageio.imread(img)
  File "/Users/tkumlehn/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-225/core/lib/imageio/core/functions.py", line 181, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/Users/tkumlehn/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-225/core/lib/imageio/core/functions.py", line 107, in get_reader
    raise ValueError('Could not find a format to read the specified file '
ValueError: Could not find a format to read the specified file in mode 'i'
ERROR:BlenderGIS-225:96:Uncaught exception
Traceback (most recent call last):
  File "/Users/tkumlehn/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-225/__init__.py", line 117, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/Applications/Blender 3.1.2.app/Contents/Resources/3.1/python/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tkumlehn/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-225/operators/view3d_mapviewer.py", line 158, in run
    self.mosaic.save(self.imgPath)
  File "/Users/tkumlehn/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-225/core/georaster/npimg.py", line 393, in save
    imageio.imwrite(path, self.data)#float32 support ok
  File "/Users/tkumlehn/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-225/core/lib/imageio/core/functions.py", line 220, in imwrite
    writer = get_writer(uri, format, 'i', **kwargs)
  File "/Users/tkumlehn/Library/Application Support/Blender/3.1/scripts/addons/BlenderGIS-225/core/lib/imageio/core/functions.py", line 148, in get_writer
    raise ValueError('Could not find a format to write the specified file '
ValueError: Could not find a format to write the specified file in mode 'i'

**Comment by domlysz** [comment]
duplicate #656

**Comment by domlysz** [comment]
@Gifted0ne please report error message
