### ISSUE TITLE
BigTIFF file not supported

### ISSUE THREAD

**Issue by plutext** [domlysz/BlenderGIS#685]
# **Blender and OS versions**

Blender 3.1.2 on Windows

# **Describe the bug**

Can't import a large tiff file; error is BigTIFF file not supported

# **How to Reproduce**

# **Error message**

INFO:BlenderGIS-225:92:###### Starting new Blender session : 2022-06-29 19:21:58
DEBUG:BlenderGIS-225.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-225.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-225.core.checkdeps:31:Pillow unavailable
DEBUG:BlenderGIS-225.core.checkdeps:46:ImageIO Freeimage plugin available
ERROR:BlenderGIS-225.operators.io_import_georaster:259:Unable to open raster
Traceback (most recent call last):
  File "C:\Users\jharr\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlenderGIS-225\operators\io_import_georaster.py", line 257, in execute
    rast = bpyGeoRaster(filePath)
  File "C:\Users\jharr\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlenderGIS-225\operators\utils\georaster_utils.py", line 223, in __init__
    GeoRaster.__init__(self, path, subBoxGeo=subBoxGeo, useGDAL=useGDAL)
  File "C:\Users\jharr\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlenderGIS-225\core\georaster\georaster.py", line 69, in __init__
    self._fromTIFF()
  File "C:\Users\jharr\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlenderGIS-225\core\georaster\georaster.py", line 125, in _fromTIFF
    tif = Tyf.open(self.path)[0]
  File "C:\Users\jharr\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlenderGIS-225\core\lib\Tyf\__init__.py", line 479, in open
    elif first in [0x4d4d, 0x4949]: obj = TiffFile(fileobj)
  File "C:\Users\jharr\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlenderGIS-225\core\lib\Tyf\__init__.py", line 299, in __init__
    raise IOError("BigTIFF file not supported")
OSError: BigTIFF file not supported

**Comment by domlysz** [comment]
Blender itself does not support bigtiff file format
