### ISSUE TITLE
SHP file import error with `UnicodeDecodeError` with a message `invalid start byte`

### ISSUE THREAD

**Issue by temeddix** [domlysz/BlenderGIS#686]
# **Blender and OS versions**
Blender 3.2.0.0
Windows 11

# **Describe the bug**
When I try to import a SHP file, an error occurs.

# **How to Reproduce**
![image](https://user-images.githubusercontent.com/66480156/177286093-edb7979d-e3ef-4dac-9b22-2332b7f424b5.png)
![image](https://user-images.githubusercontent.com/66480156/177286182-b1f0bc63-a957-489e-a1e0-0c91e54381ce.png)
![image](https://user-images.githubusercontent.com/66480156/177286227-dfd8095c-ffe5-414b-af4c-319afc48bb7f.png)
I'll upload the problematic SHP file as well
[SHP file.zip](https://github.com/domlysz/BlenderGIS/files/9044743/SHP.file.zip)

# **Error message**
 Below is from the Blender system console. 
```
INFO:BlenderGIS-228.operators.io_import_shp:Read shapefile...
ERROR:BlenderGIS-228.operators.io_import_shp:Unable to read shapefile
Traceback (most recent call last):
  File "C:\Users\temed\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\operators\io_import_shp.py", line 357, in execute
    shp = shpReader(self.filepath)
  File "C:\Users\temed\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\core\lib\shapefile.py", line 553, in __init__
    self.load(args[0])
  File "C:\Users\temed\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\core\lib\shapefile.py", line 650, in load
    self.__dbfHeader()
  File "C:\Users\temed\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\core\lib\shapefile.py", line 900, in __dbfHeader
    fieldDesc[name] = u(fieldDesc[name], self.encoding, self.encodingErrors)
  File "C:\Users\temed\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\core\lib\shapefile.py", line 104, in u
    return v.decode(encoding, encodingErrors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 0: invalid start byte
Error: Unable to read shapefile, check logs
ERROR:BlenderGIS-228.operators.io_import_shp:Shapefile import fails
Traceback (most recent call last):
  File "C:\Users\temed\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\operators\io_import_shp.py", line 288, in execute
    bpy.ops.importgis.shapefile('INVOKE_DEFAULT', filepath=self.filepath, shpCRS=shpCRS, elevSource=self.vertsElevSource,
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.2.0.0_x64__ppwjx1n5r4v9t\Blender\3.2\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Unable to read shapefile, check logs
```

**Comment by atseewal** [comment]
As the error suggests, there appears to be something wrong with your .shp file. Are you able to open/load it in other programs?

I tried loading your .shp file as a new vector layer into [qgis](https://qgis.org/en/site/) but that failed, so I think it's something to do with your input file.

**Comment by temeddix** [comment]
Sorry for the late reply. it just works fine on QGIS, perhaps because my Windows OS is set to Korean where `CP949` encoding is used by default on the system, not `UTF8`.
