### ISSUE TITLE
Can't install the add-on - numpy error

### ISSUE THREAD

**Issue by eclisia** [domlysz/BlenderGIS#694]
# **Blender 2.23 Windows 10**

I use the latest portable Blender 2.23 under Wndows10

# **Describe the bug**

Can't install the add-on - numpy error

# **How to Reproduce**

1. Download Blender 2.23 as portable version
2. Download latest release of BlenderGIS add-on
3. From Edit/Preference menu : 
4. Select Install from 
5. Then choose the BlenderGI zip file
6. Check the checkbox to enable the plugin....

# **Error message**
```python
Traceback (most recent call last):
  File "C:\Software\WinPython\WPy64-3850\python-3.8.5.amd64\Lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Software\WinPython\WPy64-3850\python-3.8.5.amd64\Lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Software\WinPython\WPy64-3850\python-3.8.5.amd64\Lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Software\blender-3.2.1-windows-x64\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\taintuf\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\__init__.py", line 137, in <module>
    from . import prefs
  File "C:\Users\taintuf\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\prefs.py", line 12, in <module>
    from .core.proj.reproj import EPSGIO
  File "C:\Users\taintuf\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\core\__init__.py", line 8, in <module>
    from .utils import XY, BBOX
  File "C:\Users\taintuf\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\core\utils\__init__.py", line 3, in <module>
    from .gradient import Color, Stop, Gradient
  File "C:\Users\taintuf\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\core\utils\gradient.py", line 9, in <module>
    from ..maths import akima
  File "C:\Users\taintuf\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGIS-228\core\maths\akima.py", line 81, in <module>
    import numpy
  File "C:\Software\WinPython\WPy64-3850\python-3.8.5.amd64\Lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\Software\WinPython\WPy64-3850\python-3.8.5.amd64\Lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\Software\blender-3.2.1-windows-x64\3.2\python\bin\python.EXE"
  * The NumPy version is: "1.23.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by atseewal** [comment]
I was unable to reproduce the issue on Windows 10 using the PortableApps version of Blender.

On the numpy troubleshooting link provided by the error:

> * whether or not you have multiple versions of Python installed

is noted as important information for troubleshooting this error.

> * The Python version is: Python3.10 from "C:\Software\blender-3.2.1-windows-x64\3.2\python\bin\python.EXE"

Looking at the traceback in your error, it looks like the version of blender you are using comes with Python 3.10. It appears to be trying to load numpy from a different version of Python's (3.8) installation location on your machine (see below quote). The version of numpy that Python 3.8 uses is likely incompatible with the Python 3.10 version packaged with your Blender.

>  import numpy
>  File "C:\Software\WinPython\WPy64-3850\python-3.8.5.amd64\Lib\site-packages\numpy\__init__.py", line 140, in <module>

You can try running https://numpy.org/devdocs/user/troubleshooting-importerror.html#check-environment-variables from the scripting tab in Blender. If it returns the Python 3.8 location in the above quote, __you can probably remedy it__ by:

* Attempting to upgrade you system Python install to 3.10, or
* Editing your system PATH variable.
