### ISSUE TITLE
i cant use open topograph 

### ISSUE THREAD

**Issue by Guilherme-html** [domlysz/BlenderGIS#717]
Python: Traceback (most recent call last):
  File "C:\Users\carne\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGIS-228\operators\io_get_dem.py", line 124, in execute
    with urlopen(rq, timeout=TIMEOUT) as response, open(filePath, 'wb') as outFile:
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\http\client.py", line 1293, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\http\client.py", line 1127, in putrequest
    self._validate_path(url)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.3\python\lib\http\client.py", line 1227, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/API/globaldem?demtype=SRTMGL1&west=-49.0449687525835&east=-48.733351561573414&south=-15.96332908111515&north=-15.747962575884591&outputFormat=GTiff&API_Key= 676326cc59cf26b05fcf459fe24276bb' (found at least ' ')

**Comment by atseewal** [comment]
Try deleting the space at the beginning of your API key.

I got the same error by adding a space at the front of the API key input. The error was resolved when I input the API key correctly.

**Comment by thpmarc** [comment]
Thank you @atseewal 
That fixed the issue for me.

**Comment by thpmarc** [comment]
Thank you @atseewal
That fixed the issue for me.

**Comment by Maple719** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderGIS-master\operators\io_get_dem.py", line 124, in execute
    with urlopen(rq, timeout=TIMEOUT) as response, open(filePath, 'wb') as outFile:
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\http\client.py", line 1294, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\http\client.py", line 1132, in putrequest
    self._output(self._encode_request(request))
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\http\client.py", line 1212, in _encode_request
    return request.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 159-160: ordinal not in range(128)

What to do?
