### ISSUE TITLE
Get elevation not working

### ISSUE THREAD

**Issue by HollabackGirlWithDisIssue** [domlysz/BlenderGIS#719]
I'm on Blender 3.3.0 and Windows 10

I'm trying to get elevation on blender but I get an error about file pathways 

https://ibb.co/NFGJHrs

I've tested this from multiple exports from different regions but I still get the same error

I choose a satellite image then export. When I try the get elevation function it gives me the error.

I have an API key and I even tried that "&API_Key="

Please if anyone can get to me about it I really wanted to test this function.

Thank you.

**Comment by atseewal** [comment]
Can you post the rest of the error? We can't see the end of the message in your screenshot.

In issue #717 there was a hint at the very end of the error that said what the invalid character in the URL was (in that case it looks like there was an extra space character included in the API key).

**Comment by HollabackGirlWithDisIssue** [comment]
For sure

https://ibb.co/9bWLHzn

Thank you for getting back

**Comment by HollabackGirlWithDisIssue** [comment]
Solved! There was a space at the front of the key

Finally progress I really appreciate it.

**Comment by a12V09** [comment]
Hi I have an error with the elevation as well, while it does form the shape of the terrain, the image on top completely disappears...
![Screenshot 2023-11-20 221226](https://github.com/domlysz/BlenderGIS/assets/151574552/dc2b3468-32d0-4feb-8079-69140f8e5ebe)

error code :

Python: Traceback (most recent call last):
  File "C:\Users\faura\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\io_get_dem.py", line 139, in execute
    bpy.ops.importgis.georaster(
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\faura\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\io_import_georaster.py", line 474, in execute
    adjust3Dview(context, bb)
  File "C:\Users\faura\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 107, in adjust3Dview
    bpy.ops.view3d.view_selected(overrideContext)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:107

**Comment by espineliandre50-cmd** [comment]
When I try to get Elevation It basically says There Is an error dammit
