### ISSUE TITLE
Cannot install the module to blender

### ISSUE THREAD

**Issue by clues4me** [domlysz/BlenderGIS#72]
Hi sir,

I cannot install your blenderGIS module in my debian 8.7 desktop with blender 2.72
here some error displayed, please helps.

> Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 299, in enable
    mod = __import__(module_name)
  File "/home/geotech/.config/blender/2.72/scripts/addons/BlenderGIS-master/__init__.py", line 53, in <module>
    import bpy.utils.previews as iconsLib
ImportError: No module named 'bpy.utils.previews'; 'bpy.utils' is not a package

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 299, in enable
    mod = __import__(module_name)
  File "/home/geotech/.config/blender/2.72/scripts/addons/BlenderGIS-master/__init__.py", line 53, in <module>
    import bpy.utils.previews as iconsLib
ImportError: No module named 'bpy.utils.previews'; 'bpy.utils' is not a package

Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 299, in enable
    mod = __import__(module_name)
  File "/home/geotech/.config/blender/2.72/scripts/addons/BlenderGIS-master/__init__.py", line 42, in <module>
    from . import prefs
ImportError: cannot import name 'prefs'

**Comment by domlysz** [comment]
Hi,

This version of blender is too old, try the latest one v2.78
