### ISSUE TITLE
Basemap Not Loading

### ISSUE THREAD

**Issue by Cantalbyte** [domlysz/BlenderGIS#753]
<!--

# **Blender 3.2**

# **Not a bug but I was wondering if they're is a way to somehow compile a extremely detailed landscape image, for example a 1 million+ tile, when I do this it doesn't work which is to be expected, but do you know of anyway?**

# **Go above 88k tiles and it doesn't load basemap**

**Comment by atseewal** [comment]
Providing some details like your OS, version of Blender, and the steps you took to get the error (pictures are helpful!) would make it easier to diagnose the issue.

**Comment by t2beatnik** [comment]
I am also having this problem with Windows 11, Blender 3.2.2, and I used the same steps I have used before in the past: Open Blender, delete default cube, from the dropdown menu I select GIS>Web geodata>basemap.  Instead of loading a global map screen that's zoomable, I get a bilious-colored field and all of Blender's menus become useless.  The only option is to quit Blender.  

Here is the log file:
[blender_gis_log_01312023.txt](https://github.com/domlysz/BlenderGIS/files/10552747/blender_gis_log_01312023.txt)

**Comment by 12stations** [comment]
I am having the same problem as @t2beatnik. I am using blender 3.4 in macOS 11.2.3. If I click 'g', the 'Search function' menu pops up but nothing else seems to work.

**Comment by atseewal** [comment]
If you press escape are you able to use the menus again? When I'm loading a base map I'm unable to use any menu in Blender until I have clicked escape to save the selection.

**Have you already tried reinstalling the latest version of the plugin?** Your log looks basically the same as mine, so I'm not sure what is causing the issue.

I'm using Blender 3.4.1, Windows 10, and the latest version of BlenderGIS from releases.

**Comment by Werner602** [comment]
Same Issue: 
Monterey V 12.0.1 Apple M1 Pro. 
Blender 3.4.1 
and latest version of Blender GIS. 

I initially did not have the  API key included, but now I do. I have read all the instructions. Not sure what may be the issue anymore...

**Comment by t2beatnik** [comment]
> If you press escape are you able to use the menus again? When I'm loading a base map I'm unable to use any menu in Blender until I have clicked escape to save the selection.
> 
> **Have you already tried reinstalling the latest version of the plugin?** Your log looks basically the same as mine, so I'm not sure what is causing the issue.
> 
> I'm using Blender 3.4.1, Windows 10, and the latest version of BlenderGIS from releases.

Escape key does nothing when this happens. My work-around was to use Blender 3.2.2 portable running from a flash drive on my Windows 10 work computer (definitely against my company’s policies!). Windows 11 on my home computer may be the problem, but I have not yet tried an update of Blender to the latest version.

**Comment by RSJ2** [comment]
Same issue here. About to uninstall and forget this.

I installed blender from the Microsoft Store directly (Installation filepaths and stuff are different). Running on v3.4.
Ran it the first time, got the ImageIO issue. Got the latest plugin, the "FreeImage-3.15.4-win32.dll"

But after trying to load basemap now, i just get a grey plane on the z axis, but no map ever loads. Have tried installing/uninstalling, restarting etc.. and nothing.

This is a screenshot of the freeze screen, once this appears the only buttons that work are minimize/close blender.
![image](https://user-images.githubusercontent.com/68808685/217213699-d030e865-8d02-40cb-ad99-9eb225b9c977.png)

**Comment by mvanec** [comment]
I just installed this in Blender 3.4.1 on Windows 11. I was getting the same issue, hitting G, using Google, and entering a location (e.g., Arches National Park, Utah)...the screen would just be that grey. Pressing Esc freed up the menus. 

Then I remember something about the opentopography.org from the documentation, went and got an API key, and entered that in BlenderGIS preferences. Now, I get this, so I reckon, make sure you have the Open Topography API key entered in your preferences? It would be handy if an error message popped up if it is missing, though.

![image](https://user-images.githubusercontent.com/112896707/217329762-4cfc22e0-da8f-42f5-9571-109e19768669.png)

**Comment by SanekTheDrone** [comment]
Hello everyone same issue as mentioned
MacBook pro m1,
MacOs Venture latest build,
Latest blender and BlenderGIS versions,
API key is also entered in preferences. 
Blank grey page same as commented above 

<img width="1507" alt="Screenshot 2023-02-07 at 23 11 22" src="https://user-images.githubusercontent.com/40390416/217354379-49ea0bdf-813a-4a52-a6b4-7e29c05b194a.png">

**Comment by t2beatnik** [comment]
The API key was not the source of the problem for me. In fact, I was able to download a basemap on my work computer, and then return to my home computer (where the problem occurred) and download the elevation data from Opentopography to that basemap using the API key.

**Comment by sjsysanti** [comment]
Same issue here.
Macbook Pro. macOS Monterey. M1 Pro
Blender 3.4.1
BlenderGIS 2.2.8
API key is right.I checked it many times.

https://drive.google.com/file/d/13MyLAhsKbj3Qu0uzUVZoMkcpwon1nD1G/view?usp=share_link

**Comment by ObaShion** [comment]
Same issue here
M1 Macbook Pro
Blender 3.4.1
BlenderGIS 2.2.8

**Comment by iridophore** [comment]
Had same issue with Windows 10, Blender 3.2, BlenderGIS 2.2.8 
so upgraded to Blender 3.4.1 and added BlenderGIS 2.2.8.
I pip installed into Blender 3.4 python:
GDAL-3.4.3-cp310-cp310-win_amd64
numpy-1.22.4+mkl-cp310-cp310-win_amd64

It now gets a python exception:
[bgis.log](https://github.com/domlysz/BlenderGIS/files/10734632/bgis.log)

Opened Blender and selected Web geodata -> Basemap

**Comment by MaxLenormand** [comment]
Same issue here

M1 Pro
Blender-GIS 2.2.8
Was on Blender 3.2.2, about to install 3.4.1 but seems like that wouldn't fix much

**Comment by dinonovak** [comment]
M1 Macbook Pro
Blender 3.4.1
BlenderGIS 2.2.8

This is log when trying to open basemap:

1) BING MAP
`DEBUG:BlenderGIS-228.operators.view3d_mapviewer:201:Bounding box request : (-434563462.1842417, -258609092.04912367, 434563462.1842417, 258609092.04912367)
DEBUG:BlenderGIS-228.core.basemaps.mapservice:726:299 tiles requested, 0 already in cache, 299 remains to download
DEBUG:BlenderGIS-228.core.basemaps.mapservice:580:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/?it=G
ERROR:BlenderGIS-228.core.basemaps.mapservice:590:Can't download tile x0 y0. Error HTTP Error 400: Bad Request
DEBUG:BlenderGIS-228.core.basemaps.mapservice:600:Invalid tile data for request http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/?it=G
ERROR:BlenderGIS-228:96:Uncaught exception
Traceback (most recent call last):
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/__init__.py", line 117, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/Applications/Blender.app/Contents/Resources/3.4/python/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/operators/view3d_mapviewer.py", line 158, in run
    self.mosaic.save(self.imgPath)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/georaster/npimg.py", line 393, in save
    imageio.imwrite(path, self.data)#float32 support ok
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 220, in imwrite
    writer = get_writer(uri, format, 'i', **kwargs)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 148, in get_writer
    raise ValueError('Could not find a format to write the specified file '
ValueError: Could not find a format to write the specified file in mode 'I'`


2) GOOGLE MAP
`DEBUG:BlenderGIS-228.operators.view3d_mapviewer:201:Bounding box request : (-434563462.1842417, -258609092.04912367, 434563462.1842417, 258609092.04912367)
DEBUG:BlenderGIS-228.core.basemaps.mapservice:726:299 tiles requested, 1 already in cache, 298 remains to download
ERROR:BlenderGIS-228.core.basemaps.mapservice:885:Corrupted tile on cache
Traceback (most recent call last):
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/basemaps/mapservice.py", line 883, in getImage
    img = NpImage(data)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/georaster/npimg.py", line 122, in __init__
    self.data = self._npFromBLOB(data)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/georaster/npimg.py", line 242, in _npFromBLOB
    data = self._npFromImgIO(img)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/georaster/npimg.py", line 258, in _npFromImgIO
    data = imageio.imread(img)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 181, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 107, in get_reader
    raise ValueError('Could not find a format to read the specified file '
ValueError: Could not find a format to read the specified file in mode 'i'
ERROR:BlenderGIS-228:96:Uncaught exception
Traceback (most recent call last):
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/__init__.py", line 117, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/Applications/Blender.app/Contents/Resources/3.4/python/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/operators/view3d_mapviewer.py", line 158, in run
    self.mosaic.save(self.imgPath)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/georaster/npimg.py", line 393, in save
    imageio.imwrite(path, self.data)#float32 support ok
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 220, in imwrite
    writer = get_writer(uri, format, 'i', **kwargs)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 148, in get_writer
    raise ValueError('Could not find a format to write the specified file '
ValueError: Could not find a format to write the specified file in mode 'i'`

**Comment by dinonovak** [comment]
M1 Macbook Pro
Blender 3.4.1
BlenderGIS 2.2.8

This is log when trying to open basemap:

1) BING MAP
`DEBUG:BlenderGIS-228.operators.view3d_mapviewer:201:Bounding box request : (-434563462.1842417, -258609092.04912367, 434563462.1842417, 258609092.04912367)
DEBUG:BlenderGIS-228.core.basemaps.mapservice:726:299 tiles requested, 0 already in cache, 299 remains to download
DEBUG:BlenderGIS-228.core.basemaps.mapservice:580:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/?it=G
ERROR:BlenderGIS-228.core.basemaps.mapservice:590:Can't download tile x0 y0. Error HTTP Error 400: Bad Request
DEBUG:BlenderGIS-228.core.basemaps.mapservice:600:Invalid tile data for request http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/?it=G
ERROR:BlenderGIS-228:96:Uncaught exception
Traceback (most recent call last):
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/__init__.py", line 117, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/Applications/Blender.app/Contents/Resources/3.4/python/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/operators/view3d_mapviewer.py", line 158, in run
    self.mosaic.save(self.imgPath)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/georaster/npimg.py", line 393, in save
    imageio.imwrite(path, self.data)#float32 support ok
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 220, in imwrite
    writer = get_writer(uri, format, 'i', **kwargs)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 148, in get_writer
    raise ValueError('Could not find a format to write the specified file '
ValueError: Could not find a format to write the specified file in mode 'I'`


2) GOOGLE MAP
`DEBUG:BlenderGIS-228.operators.view3d_mapviewer:201:Bounding box request : (-434563462.1842417, -258609092.04912367, 434563462.1842417, 258609092.04912367)
DEBUG:BlenderGIS-228.core.basemaps.mapservice:726:299 tiles requested, 1 already in cache, 298 remains to download
ERROR:BlenderGIS-228.core.basemaps.mapservice:885:Corrupted tile on cache
Traceback (most recent call last):
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/basemaps/mapservice.py", line 883, in getImage
    img = NpImage(data)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/georaster/npimg.py", line 122, in __init__
    self.data = self._npFromBLOB(data)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/georaster/npimg.py", line 242, in _npFromBLOB
    data = self._npFromImgIO(img)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/georaster/npimg.py", line 258, in _npFromImgIO
    data = imageio.imread(img)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 181, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 107, in get_reader
    raise ValueError('Could not find a format to read the specified file '
ValueError: Could not find a format to read the specified file in mode 'i'
ERROR:BlenderGIS-228:96:Uncaught exception
Traceback (most recent call last):
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/__init__.py", line 117, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/Applications/Blender.app/Contents/Resources/3.4/python/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/operators/view3d_mapviewer.py", line 158, in run
    self.mosaic.save(self.imgPath)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/georaster/npimg.py", line 393, in save
    imageio.imwrite(path, self.data)#float32 support ok
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 220, in imwrite
    writer = get_writer(uri, format, 'i', **kwargs)
  File "/Users/dino/Library/Application Support/Blender/3.4/scripts/addons/BlenderGIS-228/core/lib/imageio/core/functions.py", line 148, in get_writer
    raise ValueError('Could not find a format to write the specified file '
ValueError: Could not find a format to write the specified file in mode 'i'`

**Comment by RSJ2** [comment]
> Looks like you need to use Blender < 2.9 release for plugin to work

Is this confirmed? thanks for the comment, sucks for the plug-in.
Ae there other real life map generation alternatives for blender?

**Comment by MaxLenormand** [comment]
> Looks like you need to use Blender < 2.9 release for plugin to work

I just tried using 2.83.20 and I am once again stuck at the same place: When opening a basemap, it opens up but everything else freezes. I can't click on anything nor can I zoom in or out:

<img width="1800" alt="CleanShot 2023-02-20 at 17 31 13@2x" src="https://user-images.githubusercontent.com/44133329/220066928-fb6c1c20-bab8-4860-a2a4-bb7086a2b6f0.png">

**Comment by t2beatnik** [comment]
> > Looks like you need to use Blender < 2.9 release for plugin to work
> 
> Is this confirmed? thanks for the comment, sucks for the plug-in. Ae there other real life map generation alternatives for blender?

Not necessarily, although it may be a work-around.  As I posted a couple of weeks ago, I was able to get it to work in 3.2.2, but not on my personal PC (which is Win 11).  I had to use my Win 10 work PC, violating multiple company IT policies along the way, no doubt.

**Comment by dinonovak** [comment]
for me on MacOS,  Blender old version trick works. All basemap's are showing up.

**Comment by MaxLenormand** [comment]
> for me on MacOS, Blender old version trick works. All basemap's are showing up.

Which Blender & BlenderGIS versions are you using?

**Comment by sjsysanti** [comment]
Blender 3.4.1 BlenderGIS 2.2.8

**Comment by SanekTheDrone** [comment]
> > for me on MacOS, Blender old version trick works. All basemap's are showing up.
> 
> Which Blender & BlenderGIS versions are you using? 

As mentioned by @dinonovak, works very well.

**Comment by nickolanack** [comment]
hack*
on my mac with m1, and blender 
```bash
brew install freeimage
cp /opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage*  ~/Library/Application\ Support/Blender/3.4/scripts/addons/BlenderGIS-master/core/lib/imageio/resources
```

**Comment by RSJ2** [comment]
> > > Looks like you need to use Blender < 2.9 release for plugin to work
> > 
> > 
> > Is this confirmed? thanks for the comment, sucks for the plug-in. Ae there other real life map generation alternatives for blender?
> 
> Not necessarily, although it may be a work-around. As I posted a couple of weeks ago, I was able to get it to work in 3.2.2, but not on my personal PC (which is Win 11). I had to use my Win 10 work PC, violating multiple company IT policies along the way, no doubt.

😃 Genius! However, i can only run the Microsoft store version of Blender so its always on latest release.
This plug-in looks amazing and will try on my personal pc with older versions which seems to be the only work around.
Worst come worse I’ll ask the gods of the community to send me a .blend file with a specific box of coordinates 🙏.

**Comment by colingoodman** [comment]
Like others earlier I was only able to get the basemap to load by using an older Blender version (2.83.9). I unfortunately encountered several other significant bugs, meaning the plugin itself may not be worth messing with.

**Comment by the-mitacek** [comment]
> hack* on my mac with m1, and blender 3.4.1
> 
> ```shell
> brew install freeimage
> cp /opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage*  ~/Library/Application\ Support/Blender/3.4/scripts/addons/BlenderGIS-master/core/lib/imageio/resources
> ```

Can someone explain this solution a little bit deeper please? I'd like totry, got a same problem on M1, MacOS 13.4, Blender 3.6. Thanks!

**Comment by nickolanack** [comment]
> > hack* on my mac with m1, and blender 3.4.1
> > ```shell
> > brew install freeimage
> > cp /opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage*  ~/Library/Application\ Support/Blender/3.4/scripts/addons/BlenderGIS-master/core/lib/imageio/resources
> > ```
> 
> Can someone explain this solution a little bit deeper please? I'd like totry, got a same problem on M1, MacOS 13.4, Blender 3.6. Thanks!

You will need to alter the path in the `cp` command version/path for blender (it is platform/version specific so you might have to browse around your system for correct paths) 

Most likely you just need to replace the copy `cp` command with 
```bash
cp /opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage*  ~/Library/Application\ Support/Blender/3.6/scripts/addons/BlenderGIS-master/core/lib/imageio/resources
```
^^^ just changed 3.4 to 3.6

**Comment by lafu552** [comment]
May require freeimage to be installed    
`
ValueError: Could not find a format to read the specified file in mode 'i'
ERROR:BlenderGIS-228:96:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderGIS-228\__init__.py", line 117, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "D:\blender\3.6\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderGIS-228\operators\view3d_mapviewer.py", line 158, in run
    self.mosaic.save(self.imgPath)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderGIS-228\core\georaster\npimg.py", line 393, in save
    imageio.imwrite(path, self.data)#float32 support ok
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderGIS-228\core\lib\imageio\core\functions.py", line 220, in imwrite
    writer = get_writer(uri, format, 'i', **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlenderGIS-228\core\lib\imageio\core\functions.py", line 148, in get_writer
    raise ValueError('Could not find a format to write the specified file '
ValueError: Could not find a format to write the specified file in mode 'i'
INFO:BlenderGIS-228:92:###### Starting new Blender session : 2023-07-27 10:50:39
DEBUG:BlenderGIS-228.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-228.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-228.core.checkdeps:31:Pillow unavailable
DEBUG:BlenderGIS-228.core.checkdeps:46:ImageIO Freeimage plugin available
DEBUG:BlenderGIS-228.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -68096219.75869782, 124138625.90493649, 68096219.75869782)
DEBUG:BlenderGIS-228.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
`
Here's my log. Problem solved.

**Comment by zolty-lionheart** [comment]
> > > hack* on my mac with m1, and blender 3.4.1
> > > ```shell
> > > brew install freeimage
> > > cp /opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage*  ~/Library/Application\ Support/Blender/3.4/scripts/addons/BlenderGIS-master/core/lib/imageio/resources
> > > ```
> > 
> > 
> > Can someone explain this solution a little bit deeper please? I'd like totry, got a same problem on M1, MacOS 13.4, Blender 3.6. Thanks!
> 
> You will need to alter the path in the `cp` command version/path for blender (it is platform/version specific so you might have to browse around your system for correct paths)
> 
> Most likely you just need to replace the copy `cp` command with
> 
> ```shell
> cp /opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage*  ~/Library/Application\ Support/Blender/3.6/scripts/addons/BlenderGIS-master/core/lib/imageio/resources
> ```
> 
> ^^^ just changed 3.4 to 3.6
> 
> this solution works because it installs the missing library onto your system (brew) then copies it (cp) into a folder that blender looks in.

it works

**Comment by rafat779123493** [comment]
I've the same problem but win 11 & blender 3.6 only empty screen & when i press esc i return to the normal blender viewport

**Comment by jemharris** [comment]
> hack* on my mac with m1, and blender 3.4.1
> 
> ```shell
> brew install freeimage
> cp /opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage*  ~/Library/Application\ Support/Blender/3.4/scripts/addons/BlenderGIS-master/core/lib/imageio/resources
> ```

Im really not good at this stuff, please be kind enough to explain for dummies how to implement this fix

**Comment by ErikSpjut** [comment]
> ```shell
> cp /opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage*  ~/Library/Application\ Support/Blender/3.6/scripts/addons/BlenderGIS-master/core/lib/imageio/resources
> ```

Step 1. Make sure you are on a Mac.
Step 2. Start a terminal. It's in the Applications/Utilities directory.
Step 3. Search the web for how to install Homebrew.
Step 4. Install Homebrew using the terminal window.
Step 5. Search the web for how to install freeimage. The command "brew install freeimage" in the terminal should work.
Step 6. Try the "cp /opt/homebrew ..." command from above.
Step 7. If that doesn't work, learn how to use ls and cd, for example type man ls in the terminal.
Step 8 Use ls and cd to see if the directory paths exist. The most likely place they don't is the 3.18.0 and 3.4. Find what the correct numbers are in your path and change the "cp /opt/homebrew ..." command to have the correct paths, and use the modified command in your terminal.
Step 9. Quit and restart Blender. Things should work now like they magically just did for me.

**Comment by jemharris** [comment]
> ```shell
> ```shell
> cp /opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage*  ~/Library/Application\ Support/Blender/3.6/scripts/addons/BlenderGIS-master/core/lib/imageio/resources
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Step 1. Make sure you are on a Mac.
> Step 2. Start a terminal. It's in the Applications/Utilities directory.
> Step 3. Search the web for how to install Homebrew.
> Step 4. Install Homebrew using the terminal window.
> Step 5. Search the web for how to install freeimage. The command "brew install freeimage" in the terminal should work.
> Step 6. Try the "cp /opt/homebrew ..." command from above.
> Step 7. If that doesn't work, learn how to use ls and cd, for example type man ls in the terminal.
> Step 8 Use ls and cd to see if the directory paths exist. The most likely place they don't is the 3.18.0 and 3.4. Find what the correct numbers are in your path and change the "cp /opt/homebrew ..." command to have the correct paths, and use the modified command in your terminal.
> Step 9. Quit and restart Blender. Things should work now like they magically just did for me.
> ```


https://github.com/domlysz/BlenderGIS/assets/148778459/2bb96662-f0ab-48a8-b036-b25e74b3b727

Thank you so much for your help, this video above is the issue that happens when I open blendergis

**Comment by joekron** [comment]
> Looks like you need to use Blender < 2.9 release for plugin to work

I can confirm that Blender 2.83 (but also 2.9) work with google satellite data. 
My issue is that the issue persists if I try to use a bing basemap.

![Blender 18_02_2024 21_56_44](https://github.com/domlysz/BlenderGIS/assets/160434026/b914fb08-3092-4efd-a3a0-0cf403c30fb5)

**Comment by trinketmage** [comment]
Update from blender `> 4.0` : [now use env variable `IMAGEIO_FREEIMAGE_LIB`](https://github.com/domlysz/BlenderGIS/issues/868).
