### ISSUE TITLE
error in export for georeferenced files

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#76]
georeferenced files can't be exported in latest master and refactoring branch.
To reproduce the error:
 - go to the gis tab, choose WGS84 latlon
 - set an origin
select the default cube and go to file -> export ->shp, choose polygon and you get this error:
```
Traceback (most recent call last):
  File "D:\Blender\2.78\scripts\addons\BlenderGIS\io_shapefile\op_export_shp.py", line 69, in execute
    wkt = EPSGIO.getEsriWkt(geoscn.crs)
  File "D:\Blender\2.78\scripts\addons\BlenderGIS\utils\proj.py", line 511, in getEsriWkt
    wkt = urllib.request.urlopen(url).read().decode('utf8')
  File "D:\Blender\2.78\python\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Blender\2.78\python\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "D:\Blender\2.78\python\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Blender\2.78\python\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "D:\Blender\2.78\python\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "D:\Blender\2.78\python\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

location: <unknown location>:-1


```

**Comment by mirlip** [comment]
the bug happens on both latest Blender builboot and 2.78c. The url generated works in firefox. Manually taking the text in the downloaded file to set wkt at line 512 in proj.py works.
wkt = 'GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]'
But of course, just for the current project.

**Comment by mirlip** [comment]
Maybe having a text file with all values would help to use it offline also and prevent problems with server/connection/firewall/whatever failure.

**Comment by domlysz** [comment]
fixed on refactoring branch
thx

**Comment by mirlip** [comment]
thank you
