### ISSUE TITLE
osm import fails

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#77]
Sometime, OSM import fails with following error:
```
[out:xml][bbox:48.35092100790091,8.718342253953992,48.394455170007674,8.824184489010726];(((way[building];way[landuse]);>););out;
Overpass query success
Exception ignored in: <bound method MAP_VIEWER.__del__ of <bpy_struct, MAP_VIEWER invalid>>
Traceback (most recent call last):
  File "D:\Blender\2.78\scripts\addons_extern\BlenderGIS\operators\view3d_mapviewer.py", line 576, in __del__
    if getattr(self, 'restart', False):
  File "D:\Blender\2.78\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MAP_VIEWER has been removed
Traceback (most recent call last):
  File "D:\Blender\2.78\scripts\addons_extern\BlenderGIS\operators\io_import_osm.py", line 205, in seed
    offset = int(htag)
ValueError: invalid literal for int() with base 10: '2.5 m'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Blender\2.78\scripts\addons_extern\BlenderGIS\operators\io_import_osm.py", line 208, in seed
    offset = float(htag)
ValueError: could not convert string to float: '2.5 m'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Blender\2.78\scripts\addons_extern\BlenderGIS\operators\io_import_osm.py", line 575, in execute
    self.build(context, result, geoscn.crs)
  File "D:\Blender\2.78\scripts\addons_extern\BlenderGIS\operators\io_import_osm.py", line 351, in build
    seed(way.id, way.tags, pts)
  File "D:\Blender\2.78\scripts\addons_extern\BlenderGIS\operators\io_import_osm.py", line 212, in seed
    offset, unit = int(htag[:i]), htag[i:].strip()
ValueError: invalid literal for int() with base 10: '2.5'
```

**Comment by domlysz** [comment]
fixed, thank you for the report
