### ISSUE TITLE
Hi i have problem to get OSM

### ISSUE THREAD

**Issue by MrGlopez** [domlysz/BlenderGIS#774]
This is the blender console problem log:

ead prefs: C:\Users\MrGlopez\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
DEBUG:BlenderGIS-228.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-228.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-228.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-228.core.checkdeps:ImageIO Freeimage plugin available
Read blend: C:\Users\MrGlopez\Desktop\Edici├│n 3D\Proyecto Villajoyosa\sin_nombre.blend
DEBUG:BlenderGIS-228.operators.io_import_osm:Requests overpass server : https://lz4.overpass-api.de/api/interpreter
DEBUG:BlenderGIS-228.operators.io_import_osm:Overpass query : [out:xml][bbox:38.49659351150427,-0.21972657221452083,38.58252616759381,-0.06591795916425719];(((way[railway];way[highway];way[natural];way[waterway];way[building];way[leisure];);>;););out;
ERROR:BlenderGIS-228.operators.io_import_osm:Overpass query failed
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\http\client.py", line 1447, in connect
    super().connect()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MrGlopez\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGIS-228\operators\io_import_osm.py", line 673, in execute
    result = api.query(query)
  File "C:\Users\MrGlopez\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGIS-228\operators\lib\osm\overpy\__init__.py", line 81, in query
    f = urlopen(req, query, timeout=TIMEOUT)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder>

**Comment by mmd-osm** [comment]
`lz4.overpass-api.de/api/interpreter` has been retired!

Use `overpass-api.de/api/interpreter` instead (without the "lz4." prefix in the name).

**Comment by FredB000** [comment]
Hello, how to modifie this ? thank you.
