### ISSUE TITLE
When i press "e" i get this error

### ISSUE THREAD

**Issue by InkKeo** [domlysz/BlenderGIS#830]
# **Blender and OS versions**

4.0 Windows 11

# **Describe the bug**

# **How to Reproduce**

![imagen_2023-11-14_195856381](https://github.com/domlysz/BlenderGIS/assets/147887443/29a8cf8e-a171-45b8-9c28-423962d25f12)

# **Error message**

Python: Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 959, in modal
    adjust3Dview(context, getBBOX.fromObj(obj))
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 107, in adjust3Dview
    bpy.ops.view3d.view_selected(overrideContext)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported

**Comment by schmoe55** [comment]
what was the fix for this? Having the same problem. API code was put into preference. Blender 4.0 being used. Feel like im missing something?
