### ISSUE TITLE
Blender 4.0 GIS issue GET ELEVATION image of terrain disappears 

### ISSUE THREAD

**Issue by a12V09** [domlysz/BlenderGIS#835]
Blender 4.0 and OS 22621.2715 

It seems when I used the GIS addon and went to the get elevation, the process seemed to work fine until the terrain came out grey . I didn't find anyone to have the same issue. I reinstalled the code file, etc but nothing changed.

How to Reproduce

![image](https://github.com/domlysz/BlenderGIS/assets/151574552/153a516d-719f-416a-9fea-9756f2a819cc)
![image](https://github.com/domlysz/BlenderGIS/assets/151574552/06754635-6d75-4073-a41a-2728bc8f3c3d)
![image](https://github.com/domlysz/BlenderGIS/assets/151574552/2e38fe35-22e4-47a3-a826-3ad8d78ae32a)

Python: Traceback (most recent call last):
  File "C:\Users\faura\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\io_get_dem.py", line 139, in execute
    bpy.ops.importgis.georaster(
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\faura\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\io_import_georaster.py", line 474, in execute
    adjust3Dview(context, bb)
  File "C:\Users\faura\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 107, in adjust3Dview
    bpy.ops.view3d.view_selected(overrideContext)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:107

**Comment by Carlomarmontes** [comment]
I have a similar issue 

![Uploading Blender Gis.png…]()

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229

**Comment by Trupe** [comment]
This error is happening again to me in Blender 5.0.1, I mean there is not report error but the image doesn't stick in the geo when apply the elevation.
