### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by KonsultInternetConsulting** [domlysz/BlenderGIS#836]
Win 11 latest Blender

Press E to get base map

# **How to Reproduce**

DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (16331881.514900874, -2177288.911458302, 16359035.769199181, -2165622.710016277)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:726:72 tiles requested, 72 already in cache, 0 remains to download
ERROR:BlenderGIS-master:96:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\daren\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 959, in modal
    adjust3Dview(context, getBBOX.fromObj(obj))
  File "C:\Users\daren\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 107, in adjust3Dview
    bpy.ops.view3d.view_selected(overrideContext)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported

**Comment by dabaden** [comment]
I just installed Blender and the add-in today; same exact issue. Finding the map I want is delightful. Press "E" and I get a Python error precisely as reported.

**Comment by dabaden** [comment]
![image](https://github.com/domlysz/BlenderGIS/assets/152557981/4bfeba19-d609-4ba3-b78c-da76edb77a8d)

**Comment by Akashic101** [comment]
I ran into the same error using a fresh install of Blender 4.0.1 and BlenderGIS 2.2.8. Error is the same as above

```
Report: Error
Python: Traceback (most recent call last):
File "C:\Users\David\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-228\operators\view3d_mapviewer.py", line 959, in modal
adjust3Dview(context, getBBOX.from Obj(obj))
File "C:\Users\David\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-228\operators\utils\bgis_utils.py", line 107, in adjust3Dview
bpy.ops.view3d.view_selected (overrideContext)
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__ C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
```

I previously had an older version of Blender installed, I believe 3.4 where this error didn't occur

**Comment by dabaden** [comment]
Would you recommend downgrading to 3.4 as a remediation?
DAB

**Comment by Akashic101** [comment]
I tried it with Version 3.6.5 and I had no problem with that one. You can download it from here: https://download.blender.org/release/Blender3.6/

**Comment by dabaden** [comment]
FABulous---that worked great.
![image](https://github.com/domlysz/BlenderGIS/assets/152557981/b067a3e0-6a3c-40eb-8d70-ac2701c8771d)

**Comment by UnboundGodz** [comment]
You can either use the addon on a older Blender version thats supported, or you will have to give this a try "https://github.com/domlysz/BlenderGIS/pull/840" <--- This does fix exporting issue that 4.0 is giving everyone.

**Comment by sandersemmel** [comment]
I'm using Blender 4.0 and I have the exact same issue:

ERROR:BlenderGIS-master:96:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\Sander\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 959, in modal
    adjust3Dview(context, getBBOX.fromObj(obj))
  File "C:\Users\Sander\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 107, in adjust3Dview
    bpy.ops.view3d.view_selected(overrideContext)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
