### ISSUE TITLE
Bender 4.0 : Shapefile import fails

### ISSUE THREAD

**Issue by ChameleonScales** [domlysz/BlenderGIS#841]
# **Blender, OS and add-on versions**

- worked on : Blender 3.6.5
- doesn't work on : Blender 4.0.2
- OS : Debian 11
- BlenderGIS add-on version : 2.2.8

# **Describe the bug**

Shapefile import fails with error message since Blender 4.0

# **How to Reproduce**

1. download the attached shapefile [test-shapefile.zip](https://github.com/domlysz/BlenderGIS/files/13612077/test-shapefile.zip)
2. try to import it with the lambert-93 EPSG:2154 projection
3. under 3.6.5 it works
4. under 4.0.2 it gives the error : `Shapefile import fails, check logs.`

# **Error message**

Here's the log (I replaced my home path by ~) :
```
INFO:BlenderGIS-master:92:###### Starting new Blender session : 2023-12-08 10:00:54
DEBUG:BlenderGIS-master.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:31:Pillow unavailable
DEBUG:BlenderGIS-master.core.checkdeps:46:ImageIO Freeimage plugin available
DEBUG:BlenderGIS-master.core.proj.srv:132:Search crs : http://epsg.io/?q=lambert-93&format=json
DEBUG:BlenderGIS-master.core.proj.srv:136:Search results : [('2154', 'RGF93 v1 / Lambert-93'), ('9793', 'RGF93 v2 / Lambert-93'), ('9794', 'RGF93 v2b / Lambert-93'), ('5698', 'RGF93 v1 / Lambert-93 + NGF-IGN69 height'), ('5699', 'RGF93 v1 / Lambert-93 + NGF-IGN78 height')]
INFO:BlenderGIS-master.operators.io_import_shp:355:Read shapefile...
INFO:BlenderGIS-master.operators.io_import_shp:365:Feature type : Point
DEBUG:BlenderGIS-master.operators.io_import_shp:381:DBF fields : ['FID']
DEBUG:BlenderGIS-master.core.proj.srv:69:http://epsg.io/trans?x=427962.5189577523&y=6867551.611374921&z=0&s_srs=2154&t_srs=4326
INFO:BlenderGIS-master.operators.io_import_shp:731:Build in 0.374544 seconds
ERROR:BlenderGIS-master:96:Uncaught exception
Traceback (most recent call last):
  File "~/.config/blender/4.0/scripts/addons/BlenderGIS-master/operators/io_import_shp.py", line 736, in execute
    adjust3Dview(context, bbox)
  File "~/.config/blender/4.0/scripts/addons/BlenderGIS-master/operators/utils/bgis_utils.py", line 107, in adjust3Dview
    bpy.ops.view3d.view_selected(overrideContext)
  File "~/programs/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "~/programs/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
ERROR:BlenderGIS-master.operators.io_import_shp:292:Shapefile import fails
Traceback (most recent call last):
  File "~/.config/blender/4.0/scripts/addons/BlenderGIS-master/operators/io_import_shp.py", line 288, in execute
    bpy.ops.importgis.shapefile('INVOKE_DEFAULT', filepath=self.filepath, shpCRS=shpCRS, elevSource=self.vertsElevSource,
  File "~/programs/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "~/.config/blender/4.0/scripts/addons/BlenderGIS-master/operators/io_import_shp.py", line 736, in execute
    adjust3Dview(context, bbox)
  File "~/.config/blender/4.0/scripts/addons/BlenderGIS-master/operators/utils/bgis_utils.py", line 107, in adjust3Dview
    bpy.ops.view3d.view_selected(overrideContext)
  File "~/programs/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "~/programs/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
Location: ~/programs/blender-4.0.2-linux-x64/4.0/scripts/modules/bpy/ops.py:107
```

**Comment by pmshoesmith** [comment]
Same issue - same logs but an EPSG:4326 - works in < 4.0

**Comment by temeddix** [comment]
Same here, importing shapefile worked well in 3.X but not in 4.X

**Comment by joseenu** [comment]
i am also ongoing the same issue ., can some one explain what should i doo..

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
