### ISSUE TITLE
don't export, Python: Traceback (most recent call last)

### ISSUE THREAD

**Issue by xlebur** [domlysz/BlenderGIS#843]
after pressing "E"
Python: Traceback (most recent call last):
  File "C:\Users\omaru\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 959, in modal
    adjust3Dview(context, getBBOX.fromObj(obj))
  File "C:\Users\omaru\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 107, in adjust3Dview
    bpy.ops.view3d.view_selected(overrideContext)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported

**Comment by manlouis** [comment]
I just installed and tested the add on and got the same type of issue when pressing E

**Comment by UnboundGodz** [comment]
@xlebur @manlouis Give this a try, https://github.com/domlysz/BlenderGIS/pull/840 This does resolve the exporting error.

**Comment by nosakail** [comment]
same problem, i have switch version 4.0 with 2.83 and it's worked

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
