### ISSUE TITLE
Blender 4

### ISSUE THREAD

**Issue by Maxcaristo** [domlysz/BlenderGIS#844]
<!--
Please respect the issue template describe here :
https://github.com/domlysz/BlenderGIS/issues/289

Issues that does not respect the template will be automatically closed.

On Blender 4 it doesn't work

**Comment by MuleCreative** [comment]
Can't seem to get this working in Blender 4.0. 
- Any ideas for work arounds or is a update coming?

Thanks guys

**Comment by PeterSunnnn** [comment]
Can't seem to get this working in Blender 4.0.

Any ideas for work arounds or is a update coming?
Thanks guys
--------------------------------------------------------

i also get this problem. hope an update, thanks

**Comment by lvcargnini** [comment]
Having same issue

**Comment by matanj83** [comment]
Same here, using Blender 4.0.2 on Ubuntu 20.04. When clicking 'e' after selecting the place I want, get the error:

Python: TypeError: temp_override() takes no positional arguments

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/.config/blender/4.0/scripts/addons/BlenderGIS-master/operators/view3d_mapviewer.py", line 959, in modal
    adjust3Dview(context, getBBOX.fromObj(obj))
  File "~/.config/blender/4.0/scripts/addons/BlenderGIS-master/operators/utils/bgis_utils.py", line 108, in adjust3Dview
    with context.temp_override(overrideContext):
SystemError: <built-in method temp_override of Context object at 0x7f047a0d2500> returned a result with an exception set

**Comment by domlysz** [comment]
fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
