### ISSUE TITLE
Error when Extruding

### ISSUE THREAD

**Issue by dageatkanname** [domlysz/BlenderGIS#860]
![Screenshot 2024-01-20 164449](https://github.com/domlysz/BlenderGIS/assets/157229279/79644cfa-67a0-4f4d-8bb9-c2fdaf5dffe1)
I get this error when i press e to extrude a google Maps basemap

**Comment by MNMX** [comment]
Same here, Blender v4.0.2 with GIS:

ERROR:BlenderGIS-228:96:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\ABCD\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-228\operators\view3d_mapviewer.py", line 959, in modal
    adjust3Dview(context, getBBOX.fromObj(obj))
  File "C:\Users\ABCD\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-228\operators\utils\bgis_utils.py", line 107, in adjust3Dview
    bpy.ops.view3d.view_selected(overrideContext)
  File "C:\Steam\steamapps\common\Blender\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Steam\steamapps\common\Blender\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported

**Comment by Idontknow-13** [comment]
Same error to me
![Screenshot](https://github.com/domlysz/BlenderGIS/assets/157355537/456b054c-3838-4453-b8a8-4632abf2e253)

**Comment by enenyifeoohaoba** [comment]
Hello, I noticed you had a similar issue as I did. Could you please share how you resolved it? I would really appreciate it. Thanks in advance for your help

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
