### ISSUE TITLE
ValueError: 1-2 args execution context is supported

### ISSUE THREAD

**Issue by AmeyKuradeAK** [domlysz/BlenderGIS#870]
# **Blender and OS versions**
Blender Version: 4.0.2
OS Version: Windows 11 Home

# **Describe the bug**

After pressing **e** the console throws error as mentioned

# **How to Reproduce**

# **Error message**

Python: Traceback (most recent call last):
  File "C:\Users\[User]\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-228\operators\view3d_mapviewer.py", line 959, in modal
    adjust3Dview(context, getBBOX.fromObj(obj))
  File "C:\Users\[User]\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-228\operators\utils\bgis_utils.py", line 107, in adjust3Dview
    bpy.ops.view3d.view_selected(overrideContext)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")

**ValueError: 1-2 args execution context is supported**

**Comment by AndreasWillibaldWeber** [comment]
I have the same issue on Ubuntu 22.04.4 LTS.

**Comment by AmeyKuradeAK** [comment]
I changed some code but yet nothing changed. Maybe the Blender GIS is closed. Or Stopped the development

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
