### ISSUE TITLE
Blender / BlenderGIS don't work everything stops

### ISSUE THREAD

**Issue by Tarma81-ITA** [domlysz/BlenderGIS#920]
BlenderGis 2.2.10
Blender 4.1.0 x64
Windows 10 22H2

# **Describe the bug**

basemap is not displayed and all blender features, menus, buttons etc. are blocked. I only have the ability to scroll up and down with the mouse and the ability to minimize or close blender

# **How to Reproduce**

I copy my opentopography api key and add it in the gis => opentopograpy apy key entry, then I edit the elevation server opentopograpy srtm 30m and srtm 90m entries adding the api key at the end. then I go to gis => web geodata => basemap
I tried to manually insert the freeimage but it doesn't change anything, blender freezes and only the mouse scroll and the close and minimize buttons work. I tried all the versions of blender from 2.83 to 4.1 and the 2.2.9 and 2.2.8 versions of blender gis. The result doesn't change.
I tried to remove freeimage that I inserted manually and restart blender, now basemap is visible but as before the problem of the block and the only functional keys does not change.  Please, can you help me?

# **Error message**

LOG WITH FREEIMAGE

INFO:BlenderGIS-2210:92:###### Starting new Blender session : 2024-08-17 11:11:48
DEBUG:BlenderGIS-2210.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:31:Pillow unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:46:ImageIO Freeimage plugin available
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -70131279.19976236, 124138625.90493649, 70131279.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 0 already in cache, 35 remains to download
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=0&y=0&z=0
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -70131279.19976236, 124138625.90493649, 70131279.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -70131279.19976236, 124138625.90493649, 70131279.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -70131279.19976236, 124138625.90493649, 70131279.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -70131279.19976236, 124138625.90493649, 70131279.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -70131279.19976236, 124138625.90493649, 70131279.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-123825529.90493649, -66374247.19976236, 124451721.90493649, 73888311.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-123825529.90493649, -66374247.19976236, 124451721.90493649, 73888311.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-123825529.90493649, -66843877.19976236, 124451721.90493649, 73418681.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
WARNING:BlenderGIS-2210.geoscene:173:Origin geo has been deleted because the property could not be updated
Traceback (most recent call last):
  File "C:\Users\qwe\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderGIS-2210\geoscene.py", line 169, in setOriginPrj
    self.lon, self.lat = reprojPt(self.crs, 4326, x, y)
    ^^^^^^^^
  File "C:\Users\qwe\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderGIS-2210\geoscene.py", line 298, in lon
    raise ValueError('Wrong longitude value '+str(v))
ValueError: Wrong longitude value -269.2967402776819
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-92047288.95246825, -26455775.59988118, 32091336.952468246, 43675503.59988118)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 0 already in cache, 35 remains to download
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=0&y=0&z=1
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=1&y=0&z=1
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=0&y=1&z=1
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=1&y=1&z=1
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-76158168.47623412, -6261724.79994059, -14088855.523765877, 28803914.79994059)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:112 tiles requested, 0 already in cache, 112 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-75786376.23811707, 5165916.100029705, -44751719.76188294, 22698735.899970293)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:32 tiles requested, 0 already in cache, 32 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-71814096.11905853, 10214428.800014853, -56296767.880941465, 18980838.699985147)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-69827956.05952926, 12738685.150007427, -62069291.94047073, 17121890.099992573)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-68834886.02976464, 14000813.325003713, -64955553.97023537, 16192415.799996287)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-67824694.27269481, 14486341.338283107, -65885028.24293018, 15582142.575779393)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-67319598.39415991, 14729105.344922803, -66349765.379277594, 15277005.963670947)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:32 tiles requested, 0 already in cache, 32 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-67067050.45489246, 14850793.096289527, -66582133.94745129, 15124743.405663598)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 0 already in cache, 35 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66940929.359282166, 14911636.971972888, -66698471.105561584, 15048612.126659924)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66877868.81147702, 14942058.909814568, -66756639.68461673, 15010546.487158088)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 0 already in cache, 35 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66846338.53757445, 14957269.87873541, -66785723.9741443, 14991513.667407168)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:104 tiles requested, 0 already in cache, 104 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66829961.90452941, 14963919.90048831, -66799654.62281434, 14981041.79482419)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:40 tiles requested, 0 already in cache, 40 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66822088.90078155, 14967722.659075942, -66806935.25992402, 14976283.606243882)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:32 tiles requested, 0 already in cache, 32 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66818152.398907624, 14969624.038369758, -66810575.57847885, 14973904.511953728)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66816184.155012585, 14970574.739376836, -66812395.744798206, 14972714.976168819)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 0 already in cache, 35 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66815200.03306507, 14971050.089880373, -66813305.827957876, 14972120.208276365)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66814707.97560846, 14971287.770800782, -66813760.87305487, 14971822.829998778)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66814461.953917325, 14971406.622612571, -66813988.40264052, 14971674.152211571)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:40 tiles requested, 0 already in cache, 40 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66814338.94307175, 14971466.048518468, -66814102.16743335, 14971599.813317966)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:32 tiles requested, 0 already in cache, 32 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66814283.17392917, 14971498.372946525, -66814164.78610997, 14971565.255346274)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-66814253.57697437, 14971515.093546461, -66814194.38306477, 14971548.534746338)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download

LOG WITHOUT FREEIMAGE

INFO:BlenderGIS-2210:92:###### Starting new Blender session : 2024-08-17 12:06:02
DEBUG:BlenderGIS-2210.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:31:Pillow unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:46:ImageIO Freeimage plugin available
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -70131279.19976236, 124138625.90493649, 70131279.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 0 already in cache, 35 remains to download
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=0&y=0&z=0
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -65121899.19976236, 124138625.90493649, 75140659.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-119285793.90493649, -75297194.19976236, 128991457.90493649, 64965364.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-121320849.90493649, -70913990.19976236, 126956401.90493649, 69348568.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
INFO:BlenderGIS-2210:92:###### Starting new Blender session : 2024-08-17 12:06:45
DEBUG:BlenderGIS-2210.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:31:Pillow unavailable
DEBUG:BlenderGIS-2210.core.checkdeps:46:ImageIO Freeimage plugin available
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -70131279.19976236, 124138625.90493649, 70131279.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-123042824.90493649, -64495731.19976236, 125234426.90493649, 75766827.19976236)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-60816968.952468246, -30682435.59988118, 63321656.952468246, 39448843.59988118)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:32 tiles requested, 0 already in cache, 32 remains to download
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=0&y=0&z=1
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=1&y=0&z=1
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=0&y=1&z=1
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=1&y=1&z=1
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-29704040.976234123, -13775787.79994059, 32365271.976234123, 21289851.79994059)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:104 tiles requested, 0 already in cache, 104 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-14108441.238117062, -5635549.899970295, 16926215.23811706, 11897269.899970295)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:104 tiles requested, 0 already in cache, 104 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-6271505.619058531, -1878516.9499851475, 9245822.61905853, 6887892.949985147)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:112 tiles requested, 0 already in cache, 112 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-2313902.0595292654, -313086.4749925737, 5444762.059529265, 4070118.4749925737)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:35 tiles requested, 0 already in cache, 35 remains to download
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=17&y=14&z=5
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=14&y=13&z=5
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=19&y=12&z=5
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=19&y=14&z=5
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=17&y=16&z=5
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=16&y=12&z=5
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=14&y=15&z=5
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=20&y=15&z=5
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=15&y=12&z=5
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=15&y=14&z=5
ERROR:BlenderGIS-2210.core.basemaps.mapservice:590:Can't download tile x20 y15. Error timed out
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:600:Invalid tile data for request http://mt0.google.com/vt/lyrs=s&x=20&y=15&z=5
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (-369344.0610146327, 743579.0125037131, 3509987.9985146327, 2935181.4874962866)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:112 tiles requested, 0 already in cache, 112 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (605380.9226176837, 1252343.8812518567, 2545046.9523823163, 2348145.1187481433)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:40 tiles requested, 0 already in cache, 40 remains to download
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=66&y=57&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=70&y=59&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=71&y=56&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=71&y=58&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=65&y=57&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=65&y=59&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=71&y=60&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=72&y=56&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=68&y=57&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=66&y=59&z=7
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (602934.9382426837, 1259681.8343768567, 2542600.9680073163, 2355483.0718731433)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:32 tiles requested, 0 already in cache, 32 remains to download
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (676314.4694926837, 1666938.2406268567, 2615980.4992573163, 2762739.4781231433)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=66&y=55&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=70&y=56&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=66&y=57&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=71&y=56&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=67&y=55&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=71&y=57&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=71&y=58&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=68&y=55&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=66&y=56&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=72&y=55&z=7
DEBUG:BlenderGIS-2210.operators.view3d_mapviewer:201:Bounding box request : (678760.4538676837, 2030166.9281268567, 2618426.4836323163, 3125968.1656231433)
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:726:28 tiles requested, 0 already in cache, 28 remains to download
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=66&y=55&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=70&y=56&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=66&y=57&z=7
DEBUG:BlenderGIS-2210.core.basemaps.mapservice:580:http://mt0.google.com/vt/lyrs=s&x=67&y=54&z=7

**Comment by Tarma81-ITA** [comment]
add a video e photo to better understand the problem
I thank anyone who can help me solve the problem

![blend1](https://github.com/user-attachments/assets/34415f6f-3c9a-422d-abc3-7c2094521d34)
![blend2](https://github.com/user-attachments/assets/ddfa0600-fd85-47e2-9a0c-5c114df1c732)

https://github.com/user-attachments/assets/55b992dc-e9b3-4a3d-b93c-ff738acf3c36

**Comment by LucasBoy** [comment]
I have the same problem,Have you found a solution?If you found ,Could you tell me? ,Thanks very much!!!

**Comment by stuarta0** [comment]
The basemap option is an operator. You navigate to the location/zoom level in the viewport, then press ESC to exit basemap mode. This is by design.
