### ISSUE TITLE
Error opening basemap using Blender GIS

### ISSUE THREAD

**Issue by philorbis** [domlysz/BlenderGIS#943]
# **Blender and OS versions**

Blender 4.3, macOS 15.2

# **Describe the bug** ERROR MESSAGE upon hitting "E" after selecting map area

. Per the errort message:
Report: Error
File "/Users/philipallsopp/Library/Application Support/Blender/4.3/scripts/addons/BlenderGIS-master/operators/view3d_mapviewer.py", line 959, in modal
File "/Users/philipal|sopp/Library/Application Support/Blender/4.3/scripts/addons/BlenderGIS-master/operators/utils/bgis_utils.py", line 108, in adjust3Dview

Python: Traceback (most recent call last):
adjust3Dview (context, getBBOX.fromObj(obj))

with context.temp_override(overrideContext):
ААААААААААААААААААААААААААААААААААААА
TypeError: temp_override() takes no positional arguments

# **How to Reproduce**
Via Blender GIS add on, select Basemap.
Chhose Google, Bing or OSM
Zoom into map area of interest
Hit "E"

Error dialog pops up

<img width="2672" alt="Screenshot 2024-12-28 at 17 09 25" src="https://github.com/user-attachments/assets/36d9da9a-e048-40ef-badd-9436db1d6cd7" />
<img width="878" alt="Screenshot 2024-12-28 at 17 07 38" src="https://github.com/user-attachments/assets/5da2b9bc-1324-47f2-997f-008556c5d44f" />

# **Error message**

**Comment by obliqueoptimist** [comment]
You need to:

1. Create a free account with opentopography.org
2. Request an API key once you've created an account
3. Copy your API key into the API key section in the BIender GIS Preferences.
4. Restart the program and you will be good to go.
