### ISSUE TITLE
Struggling to get Basemap working with OSM source?

### ISSUE THREAD

**Issue by rossoe** [domlysz/BlenderGIS#99]
In attempts to work with the 'Basemap' feature I had to revert back to **Blender 2.78c** otherwise browsing the maps was very laggy.

**Google** and **Bing** sources works fine, but as soon as I switch to **OSM** source with **Mapnik** Layer, I just get a grey background - zooming in does not help.

I get the following in console:
```
Can't download tile x1 y0
Can't download tile x1 y1
Can't download tile x5 y6
Can't download tile x1 y5
```

I then tried to install GDAL in attempts to get things working, and that seemed to completely stop any of the Basemap features working with following error:
```
location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\rossoe\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 312, in drawInfosText
    blf.draw(font_id, self.progress)
  File "D:\Program Files\Blender Foundation\blender-2.78c-windows64\2.78\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MAP_VIEWER has been removed
Traceback (most recent call last):
  File "C:\Users\rossoe\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 343, in drawZoomBox
    if self.zoomBoxMode and not self.zoomBoxDrag:
  File "D:\Program Files\Blender Foundation\blender-2.78c-windows64\2.78\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MAP_VIEWER has been removed
Traceback (most recent call last):
  File "C:\Users\rossoe\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 312, in drawInfosText
    blf.draw(font_id, self.progress)
  File "D:\Program Files\Blender Foundation\blender-2.78c-windows64\2.78\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MAP_VIEWER has been removed
Traceback (most recent call last):
  File "C:\Users\rossoe\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 343, in drawZoomBox
    if self.zoomBoxMode and not self.zoomBoxDrag:
  File "D:\Program Files\Blender Foundation\blender-2.78c-windows64\2.78\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MAP_VIEWER has been removed
Traceback (most recent call last):
  File "C:\Users\rossoe\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 312, in drawInfosText
    blf.draw(font_id, self.progress)
  File "D:\Program Files\Blender Foundation\blender-2.78c-windows64\2.78\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MAP_VIEWER has been removed
Traceback (most recent call last):
  File "C:\Users\rossoe\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 343, in drawZoomBox
    if self.zoomBoxMode and not self.zoomBoxDrag:
  File "D:\Program Files\Blender Foundation\blender-2.78c-windows64\2.78\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MAP_VIEWER has been removed
Traceback (most recent call last):
  File "C:\Users\rossoe\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 664, in modal
    self.progress = self.map.srv.report
  File "D:\Program Files\Blender Foundation\blender-2.78c-windows64\2.78\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MAP_VIEWER has been removed


location: <unknown location>:-1
```

It just crashes right out of Blender.

**Comment by domlysz** [comment]
Hi, 

I can't replicate your issue, osm works fine for me and without lags in 2.79. I can't find any clue in the error log. What is your scene projection? Can you verify is the sqlite database for osm layer exists in the cache directory (file OSM_MAPNIK_WM.gpkg)? In addon preferences you can check if gdal is available as projection or image engine, and bypass it if needed.

Hope it help

**Comment by domlysz** [comment]
Talking too fast, you're right it seems the OSM provider is now broken (I had tested it with an oldest version). I will try to investigate more tomorrow, thank you for reporting this issue.

**Comment by domlysz** [comment]
Must be fixed now

https://github.com/domlysz/BlenderGIS/commit/fe74a0a76430aaf6236065bde1268d7643b971bf
